### ISSUE TITLE
My GOG.com config

### ISSUE THREAD

**Issue by Matevoun** [jaszhix/NoMansConnect#1]
Hi,

As you asking me :
- My Windows version : Windows 10 Pro. (Ver. 1607) Fr.
- I didn't found any storage_x.hg files (?!?).
- My path to NMS install directory is : (Second drive for me) : d:\Jeux\GalaxyClient\Games\No Man's Sky

There is in this folder two sub-folders : "Binaries" and "GAMEDATA".

I hope this will help you...

Thanks for your fantastic work !!

Sincerely,

Mathieu CHARREYRE
http://mathieu.charreyre.net

**Comment by jaszhix** [comment]
Your save directory may be located in C:/Users/<you>/AppData/Roaming/HelloGames/NMS/DefaultUser. If your home directory is not on C, check that file path on D, etc. The app will not function at all without save data.

For completeness of the issue, your original comment:

> Does'nt work with GOG.com user (0.6.1).

**Comment by Matevoun** [comment]
Oki... With this directory, it's seems working for me (NMC 0.7.0) for the directory checking :
- C:\Utilisateurs\matev\AppData\Roaming\HelloGames\NMS\
But now i have only the blue wheel and nothing else...

**Comment by Matevoun** [comment]
My NMC.log files for today :

> Tue Apr 18 2017 11:26:51 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 11:26:52 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to read mods directory: Error: ENOENT: no such file or directory, scandir 'D:\\Jeux\\GalaxyClient\\Games\\No Man's Sky\\GAMEDATA\\SHADERCACHE\\GAMEDATA\\PCBANKS\\MODS'"
Tue Apr 18 2017 11:26:59 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 11:26:59 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to read mods directory: Error: ENOENT: no such file or directory, scandir 'D:\\Jeux\\GalaxyClient\\Games\\No Man's Sky\\GAMEDATA\\PCBANKS\\MODS'"
Tue Apr 18 2017 11:27:05 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 11:27:05 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to read mods directory: Error: ENOENT: no such file or directory, scandir 'D:\\Jeux\\GalaxyClient\\Games\\No Man's Sky\\Binaries\\GAMEDATA\\PCBANKS\\MODS'"
Tue Apr 18 2017 11:27:11 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 11:27:12 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to read mods directory: Error: ENOENT: no such file or directory, scandir 'D:\\Jeux\\GalaxyClient\\Games\\No Man's Sky\\GAMEDATA\\GAMEDATA\\PCBANKS\\MODS'"
Tue Apr 18 2017 11:33:12 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 11:33:13 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to read mods directory: Error: ENOENT: no such file or directory, scandir 'D:\\Jeux\\GalaxyClient\\Games\\No Man's Sky\\GAMEDATA\\GAMEDATA\\PCBANKS\\MODS'"
Tue Apr 18 2017 11:33:43 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 11:33:43 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to locate NMS install: path doesn't exist."
Tue Apr 18 2017 11:37:36 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 11:37:36 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to locate NMS install: path doesn't exist."

**Comment by jaszhix** [comment]
The app works around the last error, its not starting because the save data still isn't found. I suggest trying to set C:\Utilisateurs\matev\AppData\Roaming\HelloGames\ and C:\Utilisateurs\matev\AppData\Roaming\HelloGames\NMS\DefaultUser, and see if that helps.

**Comment by Matevoun** [comment]
When i change the NMS save directory and the NMS install directory from the app :

> Tue Apr 18 2017 11:45:14 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 11:45:14 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to read mods directory: Error: ENOENT: no such file or directory, scandir 'D:\\Jeux\\GalaxyClient\\Games\\No Man's Sky\\GAMEDATA\\PCBANKS\\MODS'"
Tue Apr 18 2017 11:46:23 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 11:46:23 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to read mods directory: Error: ENOENT: no such file or directory, scandir 'D:\\Jeux\\GalaxyClient\\Games\\No Man's Sky\\GAMEDATA\\PCBANKS\\MODS'"
Tue Apr 18 2017 11:47:03 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 11:47:03 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to read mods directory: Error: ENOENT: no such file or directory, scandir 'D:\\Jeux\\GalaxyClient\\Games\\No Man's Sky\\GAMEDATA\\PCBANKS\\MODS'"
Tue Apr 18 2017 11:47:43 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 11:47:43 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to locate NMS install: path doesn't exist."

**Comment by jaszhix** [comment]
Did you get past the loading screen?

**Comment by Matevoun** [comment]
From NMC ? I have now only blue wheel now...
Tested with local admin account.

**Comment by jaszhix** [comment]
Can you try this version? I added extra debugging to the log.

https://www.mediafire.com/?dnjb54s1acud547

**Comment by Matevoun** [comment]
Oki, should i have to uninstall and Ccleaner older version ?

**Comment by jaszhix** [comment]
It wouldn't hurt. :)

**Comment by Matevoun** [comment]
Oki... ;-)
On my way... Wait...

**Comment by Matevoun** [comment]
Uninstall ... : Done
Ccleaner registery ... : Repaired
Ccleaner clean : Ok
Install NMC Tests version : Done...
Launch NMC : Nothing asked (directory)... Blue wheel directly...
Sending you pasted log now...

**Comment by Matevoun** [comment]
> Tue Apr 18 2017 12:06:59 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 12:06:59 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to locate NMS install: path doesn't exist."
Tue Apr 18 2017 12:06:59 GMT+0200 (Paris, Madrid (heure d’été)):    "Save dir in state: C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS"
Tue Apr 18 2017 12:06:59 GMT+0200 (Paris, Madrid (heure d’été)):    "P"
Tue Apr 18 2017 12:06:59 GMT+0200 (Paris, Madrid (heure d’été)):    "a"
Tue Apr 18 2017 12:06:59 GMT+0200 (Paris, Madrid (heure d’été)):    "s"
Tue Apr 18 2017 12:06:59 GMT+0200 (Paris, Madrid (heure d’été)):    "s"
Tue Apr 18 2017 12:06:59 GMT+0200 (Paris, Madrid (heure d’été)):    "i"
Tue Apr 18 2017 12:06:59 GMT+0200 (Paris, Madrid (heure d’été)):    "g"
Tue Apr 18 2017 12:06:59 GMT+0200 (Paris, Madrid (heure d’été)):    "n"

**Comment by jaszhix** [comment]
Well that means it has the save directory, but its not valid. Still could be a bug, but to be sure, I have another build you can test. You probably don't need to uninstall/run ccleaner if it saves you time.

https://www.mediafire.com/?5gwdt9aoyop642m

By the way I've never dealt with Windows in non-English locales, is C:\Utilisateurs your actual users directory? If so that is probably the problem we're running into.

**Comment by Matevoun** [comment]
Sorry, i was on call conf.
Testing now...

**Comment by Matevoun** [comment]
The Users French directory is "Utilisateurs", but on CMD (console) it's Users.
Download : Ok
Testing now...

**Comment by jaszhix** [comment]
Well that is confusing. I guess maybe the actual path is Users and Windows is symlinking Utilisateurs, or translating Users to FR in the UIs. I hate Windows. :)

Did you try selecting the upper and child directories of C:\Users(Utilisateurs?)\matev\AppData\Roaming\HelloGames\NMS? It should find it in any case, but I think something is wrong with the Users directory being translated. If its not a symlink then its just means applications aren't aware of the actual path of your user folder.

**Comment by Matevoun** [comment]
Tested with somes upper and childs directory :

> Tue Apr 18 2017 13:03:55 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 13:03:55 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to locate NMS install: path doesn't exist."
Tue Apr 18 2017 13:03:55 GMT+0200 (Paris, Madrid (heure d’été)):    "Save dir in state: C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS"
Tue Apr 18 2017 13:03:55 GMT+0200 (Paris, Madrid (heure d’été)):    "Cannot scan install directory."
Tue Apr 18 2017 13:03:55 GMT+0200 (Paris, Madrid (heure d’été)):    {"version":"0.7.0","winVersion":"10.0.14393","machineId":null,"protected":false,"init":true,"homedir":"C:\\Users\\matev","configDir":"C:\\Users\\matev\\AppData\\Roaming\\NoMansConnect","width":1421,"height":1040,"tableData":[],"title":"NO MAN'S CONNECT","installDirectory":null,"saveDirectory":"C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS","saveFileName":"","triggerSaveDirFileDialogue":false,"triggerInstallDirFileDialogue":false,"mode":"normal","storedLocations":[],"remoteLocations":[],"remoteLength":0,"currentLocation":null,"selectedLocation":null,"username":"","profile":null,"favorites":[],"mods":[],"selectedImage":null,"autoCapture":false,"selectedGalaxy":0,"galaxyOptions":[],"remoteLocationsCache":null,"settingsOpen":false,"editorOpen":false,"view":"index","sort":"-created","search":"","searchInProgress":false,"page":1,"pageSize":60,"paginationEnabled":true,"loading":false,"maximized":false,"mapLines":false,"mapZoom":false,"transparent":false,"wallpaper":null,"filterOthers":false,"show":{"Shared":true,"Explored":true,"Center":true,"Favorite":true,"Current":true,"Selected":true,"Base":true}}
Tue Apr 18 2017 13:04:18 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 13:04:18 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to locate NMS install: path doesn't exist."
Tue Apr 18 2017 13:04:18 GMT+0200 (Paris, Madrid (heure d’été)):    "Save dir in state: C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS"
Tue Apr 18 2017 13:04:18 GMT+0200 (Paris, Madrid (heure d’été)):    {"version":"0.7.0","winVersion":"10.0.14393","machineId":null,"protected":false,"init":true,"homedir":"C:\\Users\\matev","configDir":"C:\\Users\\matev\\AppData\\Roaming\\NoMansConnect","width":1421,"height":1040,"tableData":[],"title":"NO MAN'S CONNECT","installDirectory":"C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS","saveDirectory":"C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS","saveFileName":"","triggerSaveDirFileDialogue":false,"triggerInstallDirFileDialogue":false,"mode":"normal","storedLocations":[],"remoteLocations":[],"remoteLength":0,"currentLocation":null,"selectedLocation":null,"username":"","profile":null,"favorites":[],"mods":[],"selectedImage":null,"autoCapture":false,"selectedGalaxy":0,"galaxyOptions":[],"remoteLocationsCache":null,"settingsOpen":false,"editorOpen":false,"view":"index","sort":"-created","search":"","searchInProgress":false,"page":1,"pageSize":60,"paginationEnabled":true,"loading":false,"maximized":false,"mapLines":false,"mapZoom":false,"transparent":false,"wallpaper":null,"filterOthers":false,"show":{"Shared":true,"Explored":true,"Center":true,"Favorite":true,"Current":true,"Selected":true,"Base":true}}
Tue Apr 18 2017 13:04:29 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 13:04:29 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to locate NMS install: path doesn't exist."
Tue Apr 18 2017 13:04:29 GMT+0200 (Paris, Madrid (heure d’été)):    "Save dir in state: C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS"
Tue Apr 18 2017 13:04:29 GMT+0200 (Paris, Madrid (heure d’été)):    {"version":"0.7.0","winVersion":"10.0.14393","machineId":null,"protected":false,"init":true,"homedir":"C:\\Users\\matev","configDir":"C:\\Users\\matev\\AppData\\Roaming\\NoMansConnect","width":1421,"height":1040,"tableData":[],"title":"NO MAN'S CONNECT","installDirectory":"C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS\\DefaultUser","saveDirectory":"C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS","saveFileName":"","triggerSaveDirFileDialogue":false,"triggerInstallDirFileDialogue":false,"mode":"normal","storedLocations":[],"remoteLocations":[],"remoteLength":0,"currentLocation":null,"selectedLocation":null,"username":"","profile":null,"favorites":[],"mods":[],"selectedImage":null,"autoCapture":false,"selectedGalaxy":0,"galaxyOptions":[],"remoteLocationsCache":null,"settingsOpen":false,"editorOpen":false,"view":"index","sort":"-created","search":"","searchInProgress":false,"page":1,"pageSize":60,"paginationEnabled":true,"loading":false,"maximized":false,"mapLines":false,"mapZoom":false,"transparent":false,"wallpaper":null,"filterOthers":false,"show":{"Shared":true,"Explored":true,"Center":true,"Favorite":true,"Current":true,"Selected":true,"Base":true}}
Tue Apr 18 2017 13:04:38 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 13:04:38 GMT+0200 (Paris, Madrid (heure d’été)):    "Save dir in state: C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS"
Tue Apr 18 2017 13:04:38 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to locate NMS install: path doesn't exist."
Tue Apr 18 2017 13:04:38 GMT+0200 (Paris, Madrid (heure d’été)):    {"version":"0.7.0","winVersion":"10.0.14393","machineId":null,"protected":false,"init":true,"homedir":"C:\\Users\\matev","configDir":"C:\\Users\\matev\\AppData\\Roaming\\NoMansConnect","width":1421,"height":1040,"tableData":[],"title":"NO MAN'S CONNECT","installDirectory":"C:\\Users\\matev\\AppData\\Roaming\\HelloGames","saveDirectory":"C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS","saveFileName":"","triggerSaveDirFileDialogue":false,"triggerInstallDirFileDialogue":false,"mode":"normal","storedLocations":[],"remoteLocations":[],"remoteLength":0,"currentLocation":null,"selectedLocation":null,"username":"","profile":null,"favorites":[],"mods":[],"selectedImage":null,"autoCapture":false,"selectedGalaxy":0,"galaxyOptions":[],"remoteLocationsCache":null,"settingsOpen":false,"editorOpen":false,"view":"index","sort":"-created","search":"","searchInProgress":false,"page":1,"pageSize":60,"paginationEnabled":true,"loading":false,"maximized":false,"mapLines":false,"mapZoom":false,"transparent":false,"wallpaper":null,"filterOthers":false,"show":{"Shared":true,"Explored":true,"Center":true,"Favorite":true,"Current":true,"Selected":true,"Base":true}}
Tue Apr 18 2017 13:04:48 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 13:04:48 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to locate NMS install: path doesn't exist."
Tue Apr 18 2017 13:04:48 GMT+0200 (Paris, Madrid (heure d’été)):    "Save dir in state: C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS"
Tue Apr 18 2017 13:04:48 GMT+0200 (Paris, Madrid (heure d’été)):    {"version":"0.7.0","winVersion":"10.0.14393","machineId":null,"protected":false,"init":true,"homedir":"C:\\Users\\matev","configDir":"C:\\Users\\matev\\AppData\\Roaming\\NoMansConnect","width":1421,"height":1040,"tableData":[],"title":"NO MAN'S CONNECT","installDirectory":"C:\\Users\\matev\\AppData\\Roaming","saveDirectory":"C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS","saveFileName":"","triggerSaveDirFileDialogue":false,"triggerInstallDirFileDialogue":false,"mode":"normal","storedLocations":[],"remoteLocations":[],"remoteLength":0,"currentLocation":null,"selectedLocation":null,"username":"","profile":null,"favorites":[],"mods":[],"selectedImage":null,"autoCapture":false,"selectedGalaxy":0,"galaxyOptions":[],"remoteLocationsCache":null,"settingsOpen":false,"editorOpen":false,"view":"index","sort":"-created","search":"","searchInProgress":false,"page":1,"pageSize":60,"paginationEnabled":true,"loading":false,"maximized":false,"mapLines":false,"mapZoom":false,"transparent":false,"wallpaper":null,"filterOthers":false,"show":{"Shared":true,"Explored":true,"Center":true,"Favorite":true,"Current":true,"Selected":true,"Base":true}}

**Comment by jaszhix** [comment]
One last test build (thanks for testing these) - not really trying to fix the issue but get more information because I'm still not sure what's wrong. 

https://www.mediafire.com/?5h2kq7vdb7ghvdl

Also I looked into it and translated folders are indeed symbolic links - https://superuser.com/questions/466205/how-do-translated-folders-work-how-to-create-one

**Comment by Matevoun** [comment]
> Tue Apr 18 2017 13:24:17 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 13:24:17 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to locate NMS install: path doesn't exist."
Tue Apr 18 2017 13:24:17 GMT+0200 (Paris, Madrid (heure d’été)):    "Save dir in state: C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS"

**Comment by jaszhix** [comment]
I set the last log on a 5 second timer, can you try again and leave the app open a bit longer?

**Comment by Matevoun** [comment]
Oki, retry...

**Comment by Matevoun** [comment]
> Tue Apr 18 2017 13:29:02 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 13:29:02 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to locate NMS install: path doesn't exist."
Tue Apr 18 2017 13:29:02 GMT+0200 (Paris, Madrid (heure d’été)):    "Save dir in state: C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS"
Tue Apr 18 2017 13:29:07 GMT+0200 (Paris, Madrid (heure d’été)):    {"version":"0.7.0","winVersion":"10.0.14393","machineId":null,"protected":false,"init":true,"homedir":"C:\\Users\\matev","configDir":"C:\\Users\\matev\\AppData\\Roaming\\NoMansConnect","width":1421,"height":1040,"tableData":[],"title":"NO MAN'S CONNECT","installDirectory":"C:\\Users\\matev\\AppData\\Roaming","saveDirectory":"C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS","saveFileName":"","triggerSaveDirFileDialogue":false,"triggerInstallDirFileDialogue":false,"mode":"normal","storedLocations":[],"remoteLocations":[],"remoteLength":0,"currentLocation":null,"selectedLocation":null,"username":"","profile":null,"favorites":[],"mods":[],"selectedImage":null,"autoCapture":false,"selectedGalaxy":0,"galaxyOptions":[],"remoteLocationsCache":null,"settingsOpen":false,"editorOpen":false,"view":"index","sort":"-created","search":"","searchInProgress":false,"page":1,"pageSize":60,"paginationEnabled":true,"loading":false,"maximized":false,"mapLines":false,"mapZoom":false,"transparent":false,"wallpaper":null,"filterOthers":false,"show":{"Shared":true,"Explored":true,"Center":true,"Favorite":true,"Current":true,"Selected":true,"Base":true}}

**Comment by jaszhix** [comment]
I lied, one last test! https://www.mediafire.com/?9fa9u5ld6cjcwbv

This one might actually get errors in the log.

**Comment by Matevoun** [comment]
> Tue Apr 18 2017 13:38:10 GMT+0200 (Paris, Madrid (heure d’été)):    "Initializing No Man's Connect 0.7.0"
Tue Apr 18 2017 13:38:10 GMT+0200 (Paris, Madrid (heure d’été)):    "Failed to locate NMS install: path doesn't exist."
Tue Apr 18 2017 13:38:10 GMT+0200 (Paris, Madrid (heure d’été)):    "Save dir in state: C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS"
Tue Apr 18 2017 13:38:10 GMT+0200 (Paris, Madrid (heure d’été)):    "JSON WORKER: "
Tue Apr 18 2017 13:38:12 GMT+0200 (Paris, Madrid (heure d’été)):    "AJAX WORKER: "
Tue Apr 18 2017 13:38:15 GMT+0200 (Paris, Madrid (heure d’été)):    {"version":"0.7.0","winVersion":"10.0.14393","machineId":null,"protected":false,"init":true,"homedir":"C:\\Users\\matev","configDir":"C:\\Users\\matev\\AppData\\Roaming\\NoMansConnect","width":1421,"height":1040,"tableData":[],"title":"NO MAN'S CONNECT","installDirectory":"C:\\Users\\matev\\AppData\\Roaming","saveDirectory":"C:\\Users\\matev\\AppData\\Roaming\\HelloGames\\NMS","saveFileName":"","triggerSaveDirFileDialogue":false,"triggerInstallDirFileDialogue":false,"mode":"normal","storedLocations":[],"remoteLocations":[],"remoteLength":0,"currentLocation":null,"selectedLocation":null,"username":"","profile":null,"favorites":[],"mods":[],"selectedImage":null,"autoCapture":false,"selectedGalaxy":0,"galaxyOptions":[],"remoteLocationsCache":null,"settingsOpen":false,"editorOpen":false,"view":"index","sort":"-created","search":"","searchInProgress":false,"page":1,"pageSize":60,"paginationEnabled":true,"loading":false,"maximized":false,"mapLines":false,"mapZoom":false,"transparent":false,"wallpaper":null,"filterOthers":false,"show":{"Shared":true,"Explored":true,"Center":true,"Favorite":true,"Current":true,"Selected":true,"Base":true}}

**Comment by jaszhix** [comment]
Ok, well I'll have to look into this again later. It looks like it just can't find your save data.

**Comment by Matevoun** [comment]
No pb. Waiting for you.
But i'll leave tomorrow for two months.

**Comment by jaszhix** [comment]
I'm closing this for now. Feel free to open another issue if you have problems with the newest version.
