### ISSUE TITLE
Suggestion: rescale uploaded screenshots

### ISSUE THREAD

**Issue by CrankyCat** [jaszhix/NoMansConnect#10]
I suggest resizing screenshots if either the a maximum width or height is exceeded. Scale while maintaining the current aspect, etc.

I usually can't see the entire screenshot when viewing manual screenshots plus there is a bandwidth and storage concern especially with 21:9 single monitors or manually uploaded shots from multi-monitor configurations.

Alternatively, rescale when viewing and/or have an option to open in a browser.

**Comment by CrankyCat** [comment]
Rescaling while uploading seems to work well for me.

**Comment by jaszhix** [comment]
Cool, I reopened it because it seems to be off on my ultra wide monitor, but most people are using 16:9 displays, not 21:9. Its an edge case.
