### ISSUE TITLE
Can't change user name

### ISSUE THREAD

**Issue by artdog123** [jaszhix/NoMansConnect#102]
I have been unable to change the user name even after changing the settings json file. The json is overwritten on launch. Sometimes the new user name shows for a second on launch and then switches back to explorer. I also notice the path to the nms app is showing as incorrect when that is the correct path.

Windows 10
NMC  1.54
Path to storage: C:\Users\funtimefoxy\AppData\Roaming\HelloGames\NMS
Path to install: C:\Program Files (x86)\No Mans Sky NEXT

[NMC.log](https://github.com/jaszhix/NoMansConnect/files/2342217/NMC.log)
Settings:
{"apiVersion":2,"newsId":"","maximized":false,"maintenanceTS":1535568677856,"wallpaper":null,"installDirectory":"C:\\Program Files (x86)\\No Mans Sky NEXT","saveDirectory":"C:\\Users\\funtimefoxy\\AppData\\Roaming\\HelloGames\\NMS","username":"CODEX","mapLines":false,"map3d":false,"mapDrawDistance":false,"show":{"Shared":{"color":"#0080db","value":true,"listKey":"remoteLocations"},"PS4":{"color":"#0039db","value":true,"listKey":"ps4Locations"},"Explored":{"color":"#5fcc93","value":true,"listKey":"locations"},"Center":{"color":"#ba3935","value":true,"listKey":"center"},"Favorite":{"color":"#9c317c","value":true,"listKey":"favLocations"},"Current":{"color":"#FFF","value":true,"listKey":"currentLocation"},"Selected":{"color":"#ffc356","value":true,"listKey":"selectedLocation"},"Base":{"color":"#9A9D99","value":true,"listKey":"baseLocations"}},"filterOthers":false,"useGAFormat":false,"remoteLocationsColumns":1,"sortStoredByTime":false,"sortStoredByKey":"created","filterStoredByBase":false,"filterStoredByScreenshot":false,"showHidden":false,"pollRate":60000,"mode":"normal","storedBases":[],"storedLocations":[],"favorites":[],"autoCapture":false,"autoCaptureSpaceStations":false,"backupSaveFile":true,"ps4User":false,"compactRemote":false,"offline":false,"showOnlyNames":false,"showOnlyDesc":false,"showOnlyScreenshots":false,"showOnlyGalaxy":false,"showOnlyBases":false,"showOnlyPC":false,"showOnlyCompatible":false,"showOnlyFriends":false,"sortByDistance":false,"sortByModded":false,"remoteLocations":{"results":[],"count":0,"next":null,"prev":null},"page":null}

**Comment by jaszhix** [comment]
After looking at the log it looks like the username is protected because it is CODEX. This is a hard-coded name used by the pirated version of the game, and the server blacklists it.
