### ISSUE TITLE
Planet Name:  Unknown

### ISSUE THREAD

**Issue by obxBill** [jaszhix/NoMansConnect#107]
Unless this is a feature request, ALL of the following is required:

- Description of the problem
**Planet Name is always listed as Unknown**
- Windows version
**Window 10**
- NMC version
**Abyss**
- Absolute path to your storage_x.hg files.
**C:\Users\<username>\AppData\Roaming\HelloGames\NMS\st_76561198086891064**
- Absolute path to your NMS install directory.
**D:\Games\SteamLibrary\steamapps\common\No Man's Sky**

Use Pastebin of directly attach these files (Users/<Username>/AppData/Roaming/NoMansConnect):

- NMC.log
- settings.json

- How can this bug be reproduced?
**Simply viewing the Profile and all discovered planets show name as Unknown**

**Comment by jaszhix** [comment]
This means its not registered with NMC - there's no way to pull the data, otherwise - not a bug.

**Comment by obxBill** [comment]
thx for prompt response.  How are planet discoveries registered with NMC... is there a specific setting required?  Additionally, is this similar to all fauna/flora discoveries as listing only (no detail)?

**Comment by jaszhix** [comment]
No problem. When you visit a planet while NMC is open (playing the PC version of NMS), it uploads the location to the server, and logs it on the client. When it gets discovery data from the save file, it cross-references the server data with it, and any non-matches are Unknown. Unfortunately, the game doesn't store all the metadata in the save file.
