### ISSUE TITLE
Request: Add Copy Portal (In HEX)

### ISSUE THREAD

**Issue by ukmerlin** [jaszhix/NoMansConnect#109]
Would like to see an added copy feature where you can immediately copy the portal in HEX. Would be useful when putting a number of different locations into the official Galactic Map.

**Comment by ukmerlin** [comment]
Sorry does this mean you incorporated it? I dont see it as a mod in the change log.... Ta

**Comment by jaszhix** [comment]
It will be in the next version, still testing master. I'll cut a release soon. 🙂
