### ISSUE TITLE
Feature request: Auto Image Upload

### ISSUE THREAD

**Issue by ukmerlin** [jaszhix/NoMansConnect#111]
I had turned off auto image because they are usually crazy images that get taken. It would be useful if there was a hot key that would trigger the current view to be the image for the current location. 
Is in between making it manual where you have to take an image and then go and upload it.

**Comment by ukmerlin** [comment]
Update: Auto image upload keeps reverting back to manual.

**Comment by jaszhix** [comment]
Hi @ukmerlin. Sorry I've been preoccupied lately. I can reproduce the auto image upload issue, and will hopefully be able to look into it soon.

**Comment by jaszhix** [comment]
OK, I forgot I manually disable auto-capture when NMS is set to fullscreen mode - the game image can only be captured when the game uses borderless window mode. This needs more communication from the app to prevent confusion.

**Comment by ukmerlin** [comment]
Wait, so we cannot set auto if in borderless?

**Comment by jaszhix** [comment]
Auto only works while in borderless.
