### ISSUE TITLE
No Sync, no username and no map in offline mode

### ISSUE THREAD

**Issue by Doridion** [jaszhix/NoMansConnect#112]
Hi jaszhix, sorry for asking but,

Seems that No Man's Connect can't Sync at all and not saving my username (Edited the setting.json file and constantly reinitialise the username field at start-up).  I tried in offline mode, and doesn't have any "point" on the galaxy map while having three registered addresses (personnal base included).

- Windows 7 Pro x64 - SP1
- NMC version 1.5.5
- Absolute path to your storage_x.hg files : "%AppData%\Roaming\HelloGames\NMS\DefaultUser"
- Absolute path to your NMS install directory : "%AppData%\Local\Programs\NoMansConnect"

[NMC.log from install folder](https://github.com/jaszhix/NoMansConnect/files/3028447/NMC.log)

[NMC.log from cache folder](https://github.com/jaszhix/NoMansConnect/files/3028456/NMC.log)

[settings.txt](https://github.com/jaszhix/NoMansConnect/files/3028467/settings.txt)
(Setting files not accepted by Github as json file, so converted in txt ^^)

- How can this bug be reproduced ? .... Everytime ....

Thanks in advance

**Comment by jaszhix** [comment]
Are you able to establish a normal session in online mode? Sync won't work in offline mode because it requires contacting the API, but the username and map should be showing up.
