### ISSUE TITLE
1.5.9 won't finish install.

### ISSUE THREAD

**Issue by MickCasanova** [jaszhix/NoMansConnect#115]
Unless this is a feature request, ALL of the following is required:

- Description of the problem
Installation starts normal, but somewhere close to the end I get an error screen that says:
C:\Users\MC\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\NoMansConnect.lnk
Unspecified error
I can reinstall the previous version I have, which is 1.5.5, and it installs fine. But for some reason, 1.5.9 fails with an incomplete install. 

- Windows version
Windows 7 Pro

- NMC version
1.5.9

- Absolute path to your storage_x.hg files.
C:\Users\MC\AppData\Roaming\HelloGames\NMS\DefaultUser

- Absolute path to your NMS install directory.
E:\GoG\No Mans Sky

Use Pastebin of directly attach these files (Users/<Username>/AppData/Roaming/NoMansConnect):

- NMC.log
[NMC_log_settings_json.zip](https://github.com/jaszhix/NoMansConnect/files/3510965/NMC_log_settings_json.zip)

- settings.json

- How can this bug be reproduced?
attempt to install

**Comment by jaszhix** [comment]
Can you fill out the issue template? Thanks.

**Comment by MickCasanova** [comment]
Filled out the rest as best as I could. Not sure how my old log is relevant since I couldn't even get it installed.

**Comment by MickCasanova** [comment]
Bahhh.. You can close this one. Turns out Avast doesn't like your program, and decided to quarantine it every time I tried to install. Just happened to look at the Avast notices... I added it to the exceptions, and it installed fine... Sorry to waste your time... Thanks.
