### ISSUE TITLE
Cannot write into Manually Register Location

### ISSUE THREAD

**Issue by Shero2010** [jaszhix/NoMansConnect#117]
- Description of the problem
Everything is in the title ^-^' The box were I should be able to write the location where i would like to go doesn't let me write anything (It apear, I have the little bar, but I cannot write)

- Windows version
Windows 10

- NMC version
The last update

- Absolute path to your storage_x.hg files.
What is that ?

- Absolute path to your NMS install directory.
E:\Steam\steamapps\common\No Man's Sky

- NMC.log
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/3512563/NMC.log)

- settings.json
Is there any ?

- How can this bug be reproduced?
I have no idea !

Thanks in advance for your time :D

**Comment by Shero2010** [comment]
Is there any way to fix it ? :/

**Comment by jaszhix** [comment]
Yes, I'll release a new version sometime today.

**Comment by jaszhix** [comment]
Fixed in 1.6.0
