### ISSUE TITLE
Never Stop loading

### ISSUE THREAD

**Issue by SystemL0ck** [jaszhix/NoMansConnect#118]
- The Log says unable to quary username
- Windows 10
- NMC 1.7.0 (the latest version)
- C:\Users\KHofh\AppData\Roaming\HelloGames\NMS\st_76561198162158470\save.hg
- C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky

- NMC.log
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/3522656/NMC.log)

- settings.json
[settings.txt](https://github.com/jaszhix/NoMansConnect/files/3522667/settings.txt)

**Comment by jaszhix** [comment]
Thanks. Can you try clearing your data folder (\AppData\Roaming\NoMansConnect), installing 1.6.0, and see if it still gets stuck?

https://github.com/jaszhix/NoMansConnect/releases/download/v1.6.0/NoMansConnect.Setup.1.6.0.exe

**Comment by SystemL0ck** [comment]
yeah it says me the exact same thing 

1566337748736:    Initializing No Man's Connect 1.6.0 
1566337748782:    Initializing No Man's Connect 1.6.0 
1566337750862:    No Man's Connect v1.7.0 is available. 
1566337750866:    No Man's Connect v1.7.0 is available. 
1566337751161:    API error received (404): 
1566337751161:    remoteSync: Unable to query profile by username. 
1566337751162:    Failed to download missing locations from the server. 
1566337751313:    API error received (404): 
1566337751313:    remoteSync: Unable to query profile by username. 
1566337751313:    Failed to download missing locations from the server.

**Comment by lovemecomputer** [comment]
i just tried downloading and using this app for the first time, am currently getting the same issue. not sure if i've done something wrong since it's my first time using it

```

Loading...
1566338540517: Initializing No Man's Connect 1.7.0
1566338540550: Initializing No Man's Connect 1.7.0
1566338540861: API error received (404):
1566338540862: remoteSync: Unable to query profile by username.
1566338540862: Failed to download missing locations from the server.
1566338540884: API error received (404):
1566338540884: remoteSync: Unable to query profile by username.
1566338540884: Failed to download missing locations from the server.
1566339004114: Initializing No Man's Connect 1.7.0
1566339004596: API error received (404):
1566339004596: remoteSync: Unable to query profile by username.
1566339004596: Failed to download missing locations from the server.
1566339349564: Initializing No Man's Connect 1.7.0
1566339351072: API error received (404):
1566339351072: remoteSync: Unable to query profile by username.
1566339351073: Failed to download missing locations from the server.
1566339619517: Initializing No Man's Connect 1.7.0
1566339619517: Offline mode enabled.
1566339720342: Initializing No Man's Connect 1.7.0
1566339720342: Offline mode enabled.
1566339868193: Initializing No Man's Connect 1.6.0
1566339868233: State initialized
1566339868240: Initializing No Man's Connect 1.6.0
1566339868667: No Man's Connect v1.7.0 is available.
1566339868673: No Man's Connect v1.7.0 is available.
1566339868713: API error received (404):
1566339868713: remoteSync: Unable to query profile by username.
1566339868713: Failed to download missing locations from the server.
1566339868741: API error received (404):
1566339868741: remoteSync: Unable to query profile by username.
1566339868741: Failed to download missing locations from the server.
```

**Comment by jaszhix** [comment]
I can reproduce this locally, I'll try to find a fix.

**Comment by lovemecomputer** [comment]
@jaszhix awesome, thank you!! let me know if i can test/log anything locally. i have NMS installed on a separate drive than windows (and the save directory), don't know if that might have an effect?

**Comment by jaszhix** [comment]
Thanks. In this case, I think it's server code that's causing it. There weren't issues with people creating profiles on 1.6.0, but @SystemL0ck can't now.

**Comment by SystemL0ck** [comment]
@jaszhix thanks for the fast response and help :) take all the time you need to fix it.

**Comment by jaszhix** [comment]
Pushed a new release - let me know if you have anymore issues. Thanks.

https://github.com/jaszhix/NoMansConnect/releases/download/v1.7.1/NoMansConnect.Setup.1.7.1.exe

**Comment by lovemecomputer** [comment]
in a multiplayer session but will test as soon as im done! thanks so much~

**Comment by lovemecomputer** [comment]
@jaszhix everything loaded quickly!! going to test out the teleport functionality and everything next, but yeah seems to launch fine!! rad quick updates!
