### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by curlymoe** [jaszhix/NoMansConnect#12]
Issue template for bug reports:

- Description of the problem
- Windows version
- Absolute path to your storage_x.hg files.
- Absolute path to your NMS install directory.
- What does NMC.log say?
- How can this bug be reproduced?
I use Gog version, but not galaxy, my username therefore is Explorer, so now I can't use your program because someone has protected that name.

**Comment by jaszhix** [comment]
Please pastebin your NMC.log file in ```C:\Users\jason\AppData\Roaming\NoMansConnect```.

**Comment by jaszhix** [comment]
A couple other things

- Make sure you are using 0.8.0
- You can still access the menu and change your username (new feature)

**Comment by curlymoe** [comment]
I must be getting old, tried about 6 times, then as I'm pasting the log file tried again and everything is fine. Thanks for the reply, and all your hard work.

**Comment by jaszhix** [comment]
You're not getting old, I went in the server and unprotected it so you could switch. :)
