### ISSUE TITLE
Why can't screenshots be taken in full screen?

### ISSUE THREAD

**Issue by KaneHart** [jaszhix/NoMansConnect#120]
Borderless for sure in Vulkan has a slight shuttering effect and about 5% increase in gpu usage even on capped meaning I got still 30% buffer I still shutter even in open space.

So if your just taking a screenshot when landing on a planet why not just grab it from the screenshots folder on steam instead?

It's a win win we get automatic screenshots posted as well as better performance.

Not sure if I'm missing anything here but it's an idea.

Thanks.

EDIT: Yikes my English sometimes comes of hostile lol. Wondering more if it's possible and if it could be a option / feature. Thanks.

**Comment by jaszhix** [comment]
Yeah, the borderless window capture used to work a little better with OpenGL. The challenge with steam screenshots is figuring out a way to trigger a capture through steam from the app. Worth looking into.

**Comment by jaszhix** [comment]
Added a method that uses steam's capturer in 1.8.0.
