### ISSUE TITLE
New User can't find save data

### ISSUE THREAD

**Issue by jimathy** [jaszhix/NoMansConnect#122]
- After 1.7.0 being unable to create a new profile, installed 1.7.1 and it appears to be able to find my username but can't find save data. It constantly asks me to pick the location of save or change to PS4 mode.

- Windows 10

- NMS Version
   Latest? Lost Track. Not the experimental branch

- Absolute path to your storage_x.hg files.
C:\Users\gothi\AppData\Roaming\HelloGames\NMS\st_76561197975188038

- Absolute path to your NMS install directory.
Install: C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky

- NMC.log
   [NMC.log](https://pastebin.com/KDDC0pp7)
- settings.json
   [settings.txt](https://pastebin.com/zGxSA9wH)

- How can this bug be reproduced?
  Not sure. It happens everytime I load up the app

**Comment by jaszhix** [comment]
@jimathy Is this still an issue?

**Comment by jimathy** [comment]
It seems to be working now, I have no idea what kicked it in gear but it was a good day of this error.
