### ISSUE TITLE
Can't delete tags when there's too many of them

### ISSUE THREAD

**Issue by juanminm** [jaszhix/NoMansConnect#123]
**- Description of the problem:** You cannot delete the last created tags because they are under the "Update location" and "Cancel" buttons and also hidden under its panel element when overflown.
**- Windows version:** Windows 10 1903 
**- NMC version:** 1.7.1
**- Absolute path to your storage_x.hg files:** C:\Users\<User>\AppData\Roaming\HelloGames\NMS\st_76561198036982708
**- Absolute path to your NMS install directory:** D:\SteamLibrary\steamapps\common\No Man's Sky
**- NMC.log:** https://pastebin.com/BDhd0Ay7
**- settings.json:** https://pastebin.com/pdTfQDYh
**- How can this bug be reproduced?** Type enough tags in a planet/station details until it goes under the buttons and hide under the panel when it overflows.

![imagen](https://user-images.githubusercontent.com/14891772/63462876-2fd47980-c45c-11e9-9f2c-703dfc8f31b3.png)

**Comment by jaszhix** [comment]
Fixed in 1.8.0
