### ISSUE TITLE
Favoring a Location is Buggy and Removes it from the Latest Stored Locations if unfavored. 

### ISSUE THREAD

**Issue by KaneHart** [jaszhix/NoMansConnect#124]
So my left Panel (Stored Locations) Is in order of latest places I been. That way I can easily click and upload a screenshot, etc.

When I take a place I just visited and click the Fav Icon at the bottom left where shows My Name Explored. It does not actually show it filling the Fav Icon Star though it actually has.

The 2nd issue is when you Remove a Favorite so I clicked it a 2nd time it drops off my Stored Locations list. Or at least I can't find it there.

Windows 10, NMC Version 1.7.1

Use Pastebin of directly attach these files (Users/<Username>/AppData/Roaming/NoMansConnect):

https://pastebin.com/Ru5pDieH
https://pastebin.com/VWNDUeXF

**Comment by jaszhix** [comment]
Fixed in 1.8.0
