### ISSUE TITLE
Unable to set recovery email

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [jaszhix/NoMansConnect#125]
- Unable to set a recovery email and enable user protection. All tries with various email providers (like GMail or Outlook) always return an invalid email address error.
- Windows 10 64bits 1809
- NMC 1.8.1
- Absolute path to your storage_x.hg files: C:\Users\Will\AppData\Roaming\HelloGames\NMS\st_76561197964727309\save3.hg 
- Absolute path to your NMS install directory: G:\Steam\steamapps\common\No Man's Sky

Use Pastebin of directly attach these files (Users/<Username>/AppData/Roaming/NoMansConnect):

- NMC.log
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/3530909/NMC.log)

- settings.json
[settings.txt](https://github.com/jaszhix/NoMansConnect/files/3530910/settings.txt)

- How can this bug be reproduced? Open NMC, open _Options_ menu, select _Settings_, click _Recovery Email_, enter email, click _Save_ > "Invalid email address" error message.

**Comment by jaszhix** [comment]
Fixed in 1.8.2
