### ISSUE TITLE
Discord for NMC?

### ISSUE THREAD

**Issue by KaneHart** [jaszhix/NoMansConnect#128]
Not sure if your interested but because of NMC being such a great social tool I'm wondering if you be interested in expanding as well through social media like Discord? Might be a good place to meet people, talk about ideas, and get people connected.

You can throw a Link in game too and I'm sure in the long run it could grow.

I made a video of the program I really love it I could really see it being used for some sort of cross social platform for future factions and such if it's ever added to the game or heck even done via the tool itself having some sort of faction based system.

Just an idea either way. Feel free to close this ASAP once you have read it :)

**Comment by jaszhix** [comment]
If someone wants to start a Discord server, I'm open to that. My work load currently is too full to manage one myself, though.
