### ISSUE TITLE
Increase Render Distance (LOD?) on player owned Stars on 3D Map 

### ISSUE THREAD

**Issue by KaneHart** [jaszhix/NoMansConnect#129]
Not sure if this is a bug I assume just some sort of rendering LOD or something like it. Maybe it's a limitation for performance?

Either way when you zoom far enough you lose your colors:

With Colors:
https://i.imgur.com/BQdio3P.png
Without:
https://i.imgur.com/IZBUg4m.png

Nothing major but if it's not a limitation and can be easily fixed might make it easier to see ones work at a more zoomed out view so one can compare to the rest of the stars.

Might be cool also to have some sort of option to increase their distinctiveness some how when really zoomed far out just so you get an idea you vs the galaxy :) 

Thank you!

**Comment by jaszhix** [comment]
This is intentional because the more unique textures on screen at once, the slower the frame rate becomes. I haven't revisited the 3D map in a while, and there might be other ways to improve performance, but can probably make it an option.

**Comment by jaszhix** [comment]
Added a LOD option to 1.9.0.
