### ISSUE TITLE
No option to use recovery email.

### ISSUE THREAD

**Issue by PleaseCarryMe** [jaszhix/NoMansConnect#130]
- When i try to override my username, it says i must disable username protection. I dont see how to use recovery email.
- Windows 1903
- newest nmc version

**Comment by jaszhix** [comment]
You can disable username protection by toggling "Username protection" in the Settings view. After testing this, it looks like the UI doesn't update after toggling, but does after restarting the application - request is going through to the server. I'll fix the UI bug, and in the mean time you should be able to set your email after toggling it once and restarting the app (wrench dropdown -> Restart).

**Comment by PleaseCarryMe** [comment]
My description was not good, apologies. 

I used this app before, last year probably, and since then have reformatted my computer.

Im sure i set a recovery email, but it says my name PleaseCarryMe is locked and cant be set. I dont see how to recover it.

**Comment by jaszhix** [comment]
I turned off protection for that profile. It has an email set already, truncated version: th******y@gmail.com. Might have ended up in the spam folder.

**Comment by PleaseCarryMe** [comment]
Thank you. I can confirm no email was received and it is not in spam folder. Sorry for trouble. I very much appreciate the answers.

**Comment by PleaseCarryMe** [comment]
It still says i must disable username protection when trying to change to PleaseCarryMe. I might have made a new profile on accident without capitol letters. I can override to any other random username, just not PleaseCarryMe. I am confused. Should there be some popup or option to disable it through email? Does it automatically send email?

**Comment by jaszhix** [comment]
Your profile still shows as unprotected - checked and only see PleaseCarryMe in the database. What does your username show as in NMC now? Attaching NMC.log would help here (see the [issue template](https://github.com/jaszhix/NoMansConnect/blob/master/ISSUE_TEMPLATE.md)).

**Comment by PleaseCarryMe** [comment]
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/3553646/NMC.log)

my name is currently "randomname123" because i was checking to make sure "override username" worked for a different name.

**Comment by jaszhix** [comment]
Ah, I found two profiles with your email. The profile is associated with your machine ID, and these two profiles have different IDs. The second profile has a username I can't repeat here 😉. I'll re-assign the ID, and later fix the server code so an email can only be used on one profile.

**Comment by PleaseCarryMe** [comment]
ah ya that was another name i tried once sorry :P

**Comment by jaszhix** [comment]
OK, try clearing AppData/Roaming/NoMansConnect and restart the app.

**Comment by PleaseCarryMe** [comment]
boom bang boom it worked. Im soo happy thanks
