### ISSUE TITLE
Offline mode disables save scan

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [jaszhix/NoMansConnect#131]
- Offline mode disables save scan, preventing from logging discoveries while it is active.
- Windows 10 x64 1903
- NMC 1.9.0
- Absolute path to your storage_x.hg files.
- Absolute path to your NMS install directory.

- NMC.log
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/3556324/NMC.log)

- settings.json
[settings.txt](https://github.com/jaszhix/NoMansConnect/files/3556328/settings.txt)

- How can this bug be reproduced? Enable offline mode, discovery new planets/space stations. They don't register in NMC.

**Comment by jaszhix** [comment]
Thanks. Fixed in 1.9.1.
