### ISSUE TITLE
Ummm, black selected as a friends locations on map

### ISSUE THREAD

**Issue by ukmerlin** [jaszhix/NoMansConnect#135]
Exactly as title. Map has started up and black has been selected as the pin for his stations. Barely make it out in the legend area, and of course invisible on the map blackness of space :)

**Comment by jaszhix** [comment]
Fixed in 1.9.3

**Comment by ukmerlin** [comment]
Using 1.9.3 I now do not see any friends locations on the map.

**Comment by jaszhix** [comment]
@ukmerlin Can you attach the log file?

**Comment by ukmerlin** [comment]
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/3667956/NMC.log)

**Comment by ukmerlin** [comment]
Graslama bases are showing, Bear of the forest bases are not but his colour dot is a better colour in the key.

**Comment by jaszhix** [comment]
Can you attach a screenshot? Thanks.

**Comment by ukmerlin** [comment]
Sorry, when I restarted it started showing Bears locations as well. Although it does seem absent a lot of general discoveries.
![NMC](https://user-images.githubusercontent.com/27774213/65840795-2ce66780-e2eb-11e9-958e-7a5b44281bc2.PNG)

**Comment by jaszhix** [comment]
You can now customize the color of all the dots and their shape in 1.10.0 by clicking a dot in the legend. This will pull up a color picker modal.
