### ISSUE TITLE
Favorite star not displaying under stored locations after record updated (minor bug)

### ISSUE THREAD

**Issue by djehmli** [jaszhix/NoMansConnect#137]
**Setup: Stored location settings:**
Show my location = yes
Show hidden = no
Filter by bases = no
filter by screen shots = no
sort by favorites = no
sort by time = Yes
Show universe addresses = no

**Steps to replicate:**
1. Land at new location
2. Exit craft for a save position (record created in stored location)
3. left click on stored location and select favorite star from the right corner, star appears in location dialog
4. Explore location then fly to a save a new location, location appears in stored locations, repeat step 3.
5. left click on stored location from step 2, click on three dots on upper left and choose edit details.  Edit the description and or add a screen shot (note the star on the dialogue is still filled in) 
6. select update location - Star 'favorite' under stored locations for the updated record no longer appears.
7. left click to select location from number 5.  left click favorite star to unselect as favorite then left click again to select, star shows once again under stored location.

**Note:** This possibly could be due to my data being so 'old' but I wished to make sure this was reported as a just in case.  It is minor, just a small nuisance.

Windows 10
NMS Connect version 1.9.2
C:\program files(x86)\steam\steamapps\common\No Man's Sky\Binaries
C:\Users\xxxxx\AppData\Roaming\HelloGames\NMS

**Comment by jaszhix** [comment]
Fixed in 1.9.3
