### ISSUE TITLE
Ability to remove own locations from the server

### ISSUE THREAD

**Issue by Navi943** [jaszhix/NoMansConnect#139]
Considering the increasing number of griefers in NMS, would it be possible to add an option to permanently delete one's own discoveries from the online database?

**Comment by jaszhix** [comment]
I don't think NMC is facilitating griefing, you can prevent strangers from modifying your bases in the options. It's supposed to be a repository for valid locations. I'll strip authorship from your locations if you'd like, but don't see the point in deleting them.

**Comment by jaszhix** [comment]
After thinking about this, I think an option to make a location private to one's own profile and friends might be a reasonable compromise here. Opened #140 as a placeholder issue to remind me to look into it.
