### ISSUE TITLE
Stored Locations request

### ISSUE THREAD

**Issue by Durghan** [jaszhix/NoMansConnect#14]
Just wondering, is it possible to show stored locations with the Galactic Address format? The voxel format means nothing to me and isn't used in game that I'm aware of, so seems kinda pointless to use that. And I know selecting one will show a window with the galactic address in it, but I don't want to select a few dozen till I find the right one...

Thanks.

**Comment by jaszhix** [comment]
It could be an option to have it display that way. Its actually more useful because it contains the exact coordinates, the format is ```X:Y:Z:Galaxy:SolarSystem:Planet```, where as the in-game address is cosmetic and can point you to a solar system at most.

**Comment by Durghan** [comment]
But the voxel address is only available in this app, correct? That doesn't help me in game that I'm aware of...

**Comment by jaszhix** [comment]
No, its the actual format the game uses to position you. Since hex versions only point to systems, you will end up seeing all locations from the same system showing as the same label on the menu, so for obvious UX reasons I decided not to do that.

**Comment by Durghan** [comment]
That makes sense. I just haven't got a clue how to read it as it relates to playing the game...Hehe...

**Comment by jaszhix** [comment]
Maybe a long list of numbers is exactly a great solution either. :) I would pull the system names if I could. Also when you change a location's name, it will be replaced on the menu with that label.

**Comment by Durghan** [comment]
True, but at least the Galactic Address is visible in-game...

I'm also noticing, why doesn't it pull my discoveries from the servers?

**Comment by jaszhix** [comment]
Your in-game discoveries? I don't have a way of doing that. There's no public facing API I can use to pull the info from NMS servers. So think of the app as a separate database. If you lose your app data somehow, the app will re-download them for you assuming the username matches up.

**Comment by Durghan** [comment]
I mean the star systems in the Galactic Map...I'm seeing a bunch of other players, but none of mine...

**Comment by jaszhix** [comment]
Yours should be green dots. Blue is everyone else. You can also toggle which dots show by clicking on the legend.

**Comment by Durghan** [comment]
So, it only shows things explored or shared since I started using the app? Nothing from before? Because I should have several dozen in one of the corners of the map but there's nothing...

**Comment by jaszhix** [comment]
Yes, only since using the app.

**Comment by Durghan** [comment]
Cool...
