### ISSUE TITLE
Screen Shot Every Landing - None Stored To Entry

### ISSUE THREAD

**Issue by ukmerlin** [jaszhix/NoMansConnect#141]
Not sure if this is somehow intentional but the last update switched off auto screen shot. When I turned it on, I tried Steam Back End to find that it would continuously take shots every landing on a planet but none of the shots would save to the location in NMC. I switched it to legacy and it works fine.

**Comment by jaszhix** [comment]
I tried reproducing this over the weekend, but it was associating with the correct locations. If the notifications are a problem, you can disable them in Steam's settings. You can use the legacy capturer still, but requires running NMS in borderless, or windowed mode.

**Comment by ukmerlin** [comment]
I will take another look but recently in legacy I found that some locations were not getting a screen shot and one just had a black half image. I will test with both settings again.

**Comment by ukmerlin** [comment]
OK tested again set for Steam. It is taking a screen shot at every single save, filling the screen shot folder with unnecessary shots. It also appears to be replacing any existing shots in NMC. The notifications are not necessarily a problem unless recording video but do indicate the problem. I will switch back to legacy and check its behavior

**Comment by jaszhix** [comment]
Fixed in 1.10.0.

**Comment by ukmerlin** [comment]
Not sure why but while on the other side of a portal each save was taking a new screen shot. Not only that but for some reason also every time I scanned something. The attached screen shot shows the resultant list of "discoveries".
![NMSE saves](https://user-images.githubusercontent.com/27774213/75802104-2a7cb380-5d4a-11ea-82ea-a488367e8be6.jpg)

**Comment by jaszhix** [comment]
Can you open a new issue? I haven't had time to test NMC since the new update, but should be able to investigate this weekend.
