### ISSUE TITLE
Feature Request: Check boxes for legend to turn map items off

### ISSUE THREAD

**Issue by ukmerlin** [jaszhix/NoMansConnect#143]
Pretty much as the title. Personally never need to see PS4 and can almost never see selected or current so it would help if I could strip out any/all of the detail.

**Comment by jaszhix** [comment]
Do you mean an option in the settings page to toggle the legend?

**Comment by ukmerlin** [comment]
Not the legend but the parts that it indicates, so for example as mentioned I do not need PS4 findings, if there were a checkbox next to items I could uncheck PS4 and make the map unclutter.

**Comment by jaszhix** [comment]
This functionality is already present if you just click the legend item, and it persists through the settings file. Adding a checkbox might make this more intuitive and obvious to the user.

**Comment by ukmerlin** [comment]
Ah Ha! OK so new problem, I never do or have seen current and if I switch all off except current nothing is shown.

**Comment by jaszhix** [comment]
Yeah, can reproduce that. Also not seeing the yellow selected dot when selecting from the stored list, but can through the map.

**Comment by jaszhix** [comment]
Hovering over a legend item in 1.10.0 now shows a pointer cursor, indicating it's clickable.
