### ISSUE TITLE
[Freighter spawns strand players] Teleporting to Space Station

### ISSUE THREAD

**Issue by psgrace** [jaszhix/NoMansConnect#15]
Recently I teleported to a space station, one of my own discoveries from a few days earlier. I found myself floating in space near the station, with no ship. I was not able to do anything, and solved the problem by teleporting again, to a planet this time.

It occurred to me that when I enter a new system I often summon the freighter and land in it before visiting the station, and this generates a save. Could this result in teleporting to the spot in space where the freighter was? 

Windows 10 latest update
C:\Users\New\AppData\Roaming\HelloGames\NMS\DefaultUser
C:\GOG Games\No Man's Sky

No crash, so no log.

**Comment by jaszhix** [comment]
I need to start saving the freighter position, I think that is what's missing from these records. If you give me the voxel address, I can clear this address from the server so others don't run into it.

**Comment by psgrace** [comment]
OK,
1795:1:18:0:445:0

**Comment by jaszhix** [comment]
Thanks.
