### ISSUE TITLE
New Install from Old Saves

### ISSUE THREAD

**Issue by Pontiac76** [jaszhix/NoMansConnect#150]
It's been a couple of years since I've last played NMS or used NMC.

Seems as though 1.10.0 is having a problem hitting a URL, which is isn't defined in the log file

1584562950490:    API error received (404): 
1584562950491:    remoteSync: Unable to query profile by username. 
1584562950491:    Failed to download missing locations from the server. 
1584562950562:    API error received (404): 
1584562950563:    remoteSync: Unable to query profile by username. 
1584562950564:    Failed to download missing locations from the server. 
1584562951758:    SAVE DIRECTORY:  C:\Users\Stephen\AppData\Roaming\HelloGames\NMS 
1584562954554:    API error received (403): 
1584562954554:    profile: Cannot fetch a profile by username fallback while it is protected. 

When NMC starts, it notices that my login name is locked, so it then asks me to send a token.  I click the "Send Token" button, and it just spins its wheels.

**Comment by jaszhix** [comment]
Can you provide your NMC.log file? Please see the issue template.

**Comment by Pontiac76** [comment]
Sent the log via email.

**Comment by jaszhix** [comment]
Thanks. I turned off protection for that profile in the log, and you should be able to use it now. I'll try to reproduce the email issue.

**Comment by Pontiac76** [comment]
I'm in, thanks.

I don't mind being a guinea pig.  If you'd like to leave this open to validate the email problem, I don't mind locking the account again and trying to reproduce the problem, or, if the act of my reactivating/using the account now invalidates further email tests, I guess this this can get closed.
