### ISSUE TITLE
80% Average CPU

### ISSUE THREAD

**Issue by ukmerlin** [jaszhix/NoMansConnect#151]
I am finding that the application is eating up PC performance. On average about 80% is allocating to NMSE with or without NMS. When I finish playing NMS and then shut down NMSE it takes about 30s to a minute to come back down.

**Comment by jaszhix** [comment]
Thanks for opening the issue. I'll see what can be done. I noticed you have a lot of locations, so I'm curious if that's part of it.

**Comment by jaszhix** [comment]
I can't reproduce high CPU usage with NMC. I sent a friend request to your profile on NMC. If you accept it your locations will sync with my own, and it will make it easier to see the performance impact of the extra cached locations. Also released build 1.10.1 with a more stable version of Electron, please let me know if there's any change.

**Comment by ukmerlin** [comment]
Accepted the friend request. I wonder if Graslama has the same issue he is the top user above me all time.

**Comment by ukmerlin** [comment]
Here is a screen shot of NMC and the performance tab. Note also that no items are showing on the NMC map although I think four or five types are selected to show.

![NMCPerformance](https://user-images.githubusercontent.com/27774213/77542223-3ad10b80-6e7c-11ea-971d-576ed9c65579.jpg)

**Comment by jaszhix** [comment]
What do you have the polling rate set to in the settings?

When NMC checks the server for new locations, it has to sort and merge the new locations with ones currently cached. This is an expensive routine, and I suspect 15-45 second interval options may be too frequent when a lot of locations are cached. It will scale this routine across multiple worker threads depending on how many CPU cores are available, which is probably why I haven't noticed. When setting the polling rate to 15 seconds, I can see the CPU and I/O usage is much higher.

**Comment by ukmerlin** [comment]
OK so I checked it at 15 second poll rate and 60, there was no observable difference between the two. Map still not showing any locations at all.

**Comment by jaszhix** [comment]
Try clearing the app cache in AppData/Roaming/NoMansConnect. At one point there were invalid locations uploaded causing the map to break, but both the client and server check for invalid coordinates now.

**Comment by ukmerlin** [comment]
Clearing the cache dropped the CPU usage and brought back the map items although it still does not show "current" location. "Explored" is that just mine or everyone's?

**Comment by jaszhix** [comment]
"Explored" is your own locations, "Shared" is everyone else's. Is the CPU usage still an issue?
