### ISSUE TITLE
NMC installer stuck saying Installing

### ISSUE THREAD

**Issue by TrueExcalibur11** [jaszhix/NoMansConnect#154]
Unless this is a feature request, ALL of the following is required:

- Description of the problem: The installer doesn't finish after 30 mins, stuck saying installing, but not actually doing anything
- Windows version: Windows 10
- NMC version: v1.10.1
- Absolute path to your storage_x.hg files: ????
- Absolute path to your NMS install directory: F:\SteamLibrary\steamapps\common\No Man's Sky

Use Pastebin of directly attach these files (Users/<Username>/AppData/Roaming/NoMansConnect):

- NMC.log
- settings.json
(Not installed so not possible)

If requested, please email your save file to jaszhix@gmail.com. This file will not be used in the game, or on NMC's production server.

- How can this bug be reproduced?
Idk if this happens to others, but on my PC, when running setup from Desktop with NMS in f drive it doesn't work. I previously installed NMC, but it was an old version so I deleted it from roaming. Now it won't even finish the installation. Just stuck at 1/3 with no CPU usage and very little memory in task manager. Is there anything I can do?

**Comment by jaszhix** [comment]
The installer will only install to your local user directory, the location of the game installation shouldn't affect it. Try deleting AppData/Roaming/NoMansConnect in your user directory if it exists, and reinstall. If you go to settings and configure the "NMS Save Directory" option you should be able to get the app to find the save file.

**Comment by TrueExcalibur11** [comment]
Installer is still getting stuck with nothing in AppData/Roaming. Do you have an older version installer I could try using?

**Comment by TrueExcalibur11** [comment]
I would try to just use the source code, but idk how to install from that.

**Comment by jaszhix** [comment]
The installer is based on [NSIS](https://nsis.sourceforge.io/Download), which a lot of apps use. I suspect this may be a permissions issue, but there's not enough info to tell either way.
