### ISSUE TITLE
Fresh install / Stuck at Loading / No Man's Sky not installed on this PC

### ISSUE THREAD

**Issue by quinnell** [jaszhix/NoMansConnect#159]
On a fresh install of NMC on a PC that has never had the game installed, I am getting stuck at "Loading..."

- Windows 10 1909
- 1.10.1
- NMS not installed

[https://pastebin.com/g6p6NRxj](https://pastebin.com/g6p6NRxj)

- NMC.log:
`1586356890798:    Initializing No Man's Connect 1.10.1 
1586356890843:    Initializing No Man's Connect 1.10.1 
1586356893310:    remoteSync: Unable to query profile by username. 
1586356893310:    Failed to download missing locations from the server. 
1586356893310:    API error received (404): 
1586356893338:    Failed to locate NMS install: path doesn't exist. 
1586356893402:    API error received (404): 
1586356893402:    remoteSync: Unable to query profile by username. 
1586356893402:    Failed to download missing locations from the server. 
1586356893426:    Failed to locate NMS install: path doesn't exist. 
1586356895610:    SAVE DIRECTORY:  undefined `

- settings.json
`{"apiVersion":3,"newsId":"","maximized":false,"maintenanceTS":1586356890281,"wallpaper":null,"installDirectory":null,"steamInstallDirectory":"","username":"Explorer","mapLines":false,"map3d":false,"mapDrawDistance":true,"mapLODFar":false,"mapSkyBox":true,"show":{"Shared":{"color":"#0080db","shape":"circle","value":true,"listKey":"remoteLocations"},"Manual":{"color":"#0039db","shape":"circle","value":true,"listKey":"manualLocations"},"Explored":{"color":"#5fcc93","shape":"circle","value":true,"listKey":"locations"},"Center":{"color":"#ba3935","shape":"circle","value":true,"listKey":"center"},"Favorite":{"color":"#9c317c","shape":"circle","value":true,"listKey":"favLocations"},"Current":{"color":"#FFF","shape":"star","value":true,"listKey":"currentLocation"},"Selected":{"color":"#ffc356","shape":"circle","value":true,"listKey":"selectedLocation"},"Base":{"color":"#9A9D99","shape":"triangle","value":true,"listKey":"baseLocations"}},"showMap":true,"filterOthers":false,"useGAFormat":false,"remoteLocationsColumns":1,"sortStoredByTime":false,"sortStoredByKey":"created","filterStoredByBase":false,"filterStoredByScreenshot":false,"showHidden":false,"pollRate":60000,"mode":"normal","storedBases":[],"storedLocations":[],"favorites":[],"autoCapture":false,"autoCaptureSpaceStations":false,"autoCaptureBackend":"steam","focusKey":false,"backupSaveFile":true,"ps4User":false,"compactRemote":false,"offline":false,"showOnlyNames":false,"showOnlyDesc":false,"showOnlyScreenshots":false,"showOnlyGalaxy":false,"showOnlyBases":false,"showOnlyPC":false,"showOnlyCompatible":false,"showOnlyFriends":false,"sortByDistance":false,"sortByModded":false,"sortByFavorites":false,"sortByTeleports":false,"sortByModified":false,"remoteLocations":{"results":[],"count":0,"next":null,"prev":null},"page":null}`

**Comment by astr0wax** [comment]
experiencing the same issue

**Comment by jaszhix** [comment]
Those are just labels. The app has no integration with PSN. You just need to manually input your username - the bug preventing the client from loading will be looked at soon.

**Comment by Artzfall** [comment]
Yeah, about that, when are you doing that, Chief? Really wanted to use this, but I'm having the same damn issue, a year and a half since that comment. So are you moving on that? Or is the project dead and we should all go home? And no, fixing my username did jack shit, it just switched back to "Explorer" immediately and kept spinning the wheel of annoyance at me.

**Comment by jaszhix** [comment]
> Yeah, about that, when are you doing that, Chief? Really wanted to use this, but I'm having the same damn issue, a year and a half since that comment. So are you moving on that? Or is the project dead and we should all go home? And no, fixing my username did jack shit, it just switched back to "Explorer" immediately and kept spinning the wheel of annoyance at me.

This issue is open not because it's still a verified problem, but because I can't reproduce it, and there's a number of causes to why the app might not load. There's simply not enough information here. If you're running into problems, feel free to open an issue, but please drop the attitude or I will ban you from posting here. This is a hobby project. I will only guarantee the servers continue running thanks to patron support, development is currently in maintenance mode.
