### ISSUE TITLE
Discovery Overwritten

### ISSUE THREAD

**Issue by psgrace** [jaszhix/NoMansConnect#16]
Have a look at the entry in the Recent Explorations list titled "Psaggo279 Irkutsk". I uploaded it on April 5 and it still appears in that position, but its creation date now says April 20, and that is its position in my Stored Locations list. Also there is now a mods list; I am not using mods. It appears that on April 20 someone visited this planet and partially overwrote the record. This may be something you have since fixed, and it doesn't have any real effect on me anyway; I am just mentioning it in case it is a bug you were not aware of.

**Comment by jaszhix** [comment]
Ah, yeah that has been fixed in 0.8.0. It was only one user who was accidentally impersonating others and was nice enough to let me know so I could patch it. If you give me the voxel address I can delete that record if you'd like.

**Comment by psgrace** [comment]
No, doesn't matter
