### ISSUE TITLE
Request, not an issue.

### ISSUE THREAD

**Issue by temp-999** [jaszhix/NoMansConnect#17]
Windows 10 pro 1607. I play NMS on a PC while connected to a Steam account. No mods, but I do alter the save files using nmsse and nmssavetool.

I'd like a settable switch so that it's possible to have nothing uploaded to NMC- all content to remain on the local PC. I don't wish to share locations at this time not see other's locations but I do wish to return to locations that I've visited or possibly to some that have be recommended. I like that NMS is vast and that I can remain lost in it.

However if this is a direction that doesn't align with your goals then I certainly would not expect you to act on this request. Thank you.

**Comment by temp-999** [comment]
Windows 10 pro 1607. I play NMS on a PC while connected to a Steam account. No mods, but I do alter the save files using nmsse and nmssavetool.

I'd like a settable switch so that it's possible to have nothing uploaded to NMC- all content to remain on the local PC.  I don't wish to share locations at this time not see other's locations but I do wish to return to locations that I've visited or possibly to some that have be recommended. I like that NMS is vast and that I can remain lost in it.

However if this is a direction that doesn't align with your goals then I certainly would not expect you to act on this request. Thank you.

**Comment by temp-999** [comment]
Obviously I don't comment in GitHub very much...

**Comment by CrankyCat** [comment]
Maybe a branch for a separate offline location manager?

**Comment by jaszhix** [comment]
It would be less effort to add a mode to the app, maintaining two versions would be a lot of work. I'll try to get this in next release.

**Comment by temp-999** [comment]
Thank you for considering this. I look forward to it but please do not let it hold up other work that you already have planned.

**Comment by jaszhix** [comment]
I have decided its not worth the technical debt it would introduce to add this feature. The app is too heavily designed around uploading locations, and I don't think its worth it. It also works reasonably well with no internet connection when its required. The game uploads locations as well, so I don't really understand the point. If you want to fork it and implement this yourself and create No Man's Disconnect, feel free. :)

**Comment by temp-999** [comment]
No problem. Thank you for considering it.

---------- Original Message ----------
