### ISSUE TITLE
Cannot launch program

### ISSUE THREAD

**Issue by carrsteven** [jaszhix/NoMansConnect#171]
Unless this is a feature request, ALL of the following is required:

- Description of the problem

  Program will not launch. Get error "The procedure entry point av_buffer_create could not be located in the dynamic link library" Seems to be an issue for ffmpeg but I tested it on both my pc and my laptop and get the same error.
- Windows version

  Windows 10 1809 and Windows 10 1903
- NMC version

  1.10.1
- Absolute path to your storage_x.hg files.
- Absolute path to your NMS install directory.

Use Pastebin of directly attach these files (Users/<Username>/AppData/Roaming/NoMansConnect):

- NMC.log

Doesn't create one
- settings.json

Doesn't create one

If requested, please email your save file to jaszhix@gmail.com. This file will not be used in the game, or on NMC's production server.

- How can this bug be reproduced?

**Comment by jaszhix** [comment]
This seems like an issue with your Windows installation. Try running `sfc /scannow` in an admin cmd.exe/powershell.exe prompt.

**Comment by carrsteven** [comment]
You were correct. My apologies.
