### ISSUE TITLE
Wrong Galaxy logging

### ISSUE THREAD

**Issue by Iznas** [jaszhix/NoMansConnect#173]
- Description of the problem
- Windows 10
- NMC steam latest version as of 8/17/20
- Absolute path to your storage_x.hg files. ---- no idea
- Absolute path to your NMS install directory. --- no idea

When i switched galaxies, NMC kept my save in euclid, but i was in essestam, so none of my discoveries are logging in the correct galaxy.

**Comment by jaszhix** [comment]
The issue template tells where the logs can be found. Please re-open with all required info. This isn't actionable.
