### ISSUE TITLE
Save data not found, infinite loading.

### ISSUE THREAD

**Issue by daanvy** [jaszhix/NoMansConnect#177]
- Description of the problem : 
- Windows version : Windows 10 Enterprise
- NMC version : 1.10.1
- Absolute path to your storage_x.hg files. : Can't find these
- Absolute path to your NMS install directory. : E:\WindowsApps\HelloGames.NoMansSky_3.15.1713.0_x64__bs190hzg1sesy

Use Pastebin of directly attach these files (Users/<Username>/AppData/Roaming/NoMansConnect): https://pastebin.com/MYTw6P6g

- NMC.log
- settings.json

If requested, please email your save file to jaszhix@gmail.com. This file will not be used in the game, or on NMC's production server.

- How can this bug be reproduced? Just by opening it

Things i've tried : 
-Reinstalling NMC
-Disabling anti virus
-Running as administrator

**Comment by jaszhix** [comment]
This was discussed in #165, it's currently not possible to support the XGP version of the game. I have updated the FAQ mentioning this.
