### ISSUE TITLE
NMC is incompatible with NMS Frontiers update

### ISSUE THREAD

**Issue by jaszhix** [jaszhix/NoMansConnect#186]
The new save format changed from JSON to an unknown binary format, preventing NMC from reading or writing changes. I'll continue to research this over the coming weekends as I have time, though not confident this can be resolved without more involved reverse engineering.

Ref - https://github.com/goatfungus/NMSSaveEditor/issues/404

**Comment by bdew** [comment]
Here's my implementation of decompressing saves in typescript - https://gist.github.com/bdew/69252923b4abdffd5b825b70756a5800

code is public domain, if anyone wants to integrate it into NMC - feel free to.

**Comment by jaszhix** [comment]
Thanks @bdew! This seems to work. I'll cut a quick release today.
