### ISSUE TITLE
Username protected. Also stuck on Syncing Locations now.

### ISSUE THREAD

**Issue by Cykaski** [jaszhix/NoMansConnect#187]
Unless this is a feature request, ALL of the following is required:

- Description of the problem
-Can't get my discovered locations back, Also recently stuck on syncing locations.
- Windows version
- 10
- NMC version
- 1.10.1
- Absolute path to your storage_x.hg files.
- 
- Absolute path to your NMS install directory.

Use Pastebin of directly attach these files (Users/<Username>/AppData/Roaming/NoMansConnect):

- NMC.log
- settings.json

If requested, please email your save file to jaszhix@gmail.com. This file will not be used in the game, or on NMC's production server.

- How can this bug be reproduced?

**Comment by jaszhix** [comment]
This is likely related to #186. I released a quick update that should fix save file compatibility for NMS Frontiers - please reopen if there's issues with [v1.10.2](https://github.com/jaszhix/NoMansConnect/releases/tag/v1.10.2).
