### ISSUE TITLE
How to install on Linux?

### ISSUE THREAD

**Issue by Jimi-James** [jaszhix/NoMansConnect#188]
I feel stupid, like maybe I haven't looked in the right place. But the previous version's release had an Arch Linux (.pacman) package I could just install, simple, easy. Now that this new release doesn't have that, I'm trying to figure it out, and there's no thread to grasp onto. I see no executable file in here. No install instructions in the README or the FAQ or anywhere. And the file structure has very little in common with the file structure of the previous version, so I also have no idea how to just replace the files in the old .pacman file with this new verison.

**Comment by jaszhix** [comment]
I usually lag a bit with Linux binaries as they are built on another machine, and I tagged the release 30 minutes ago 🙂. Should be uploaded to the release page shortly.
