### ISSUE TITLE
Cannot connect to server. Loop when checking for newer version. 

### ISSUE THREAD

**Issue by Spoog42** [jaszhix/NoMansConnect#195]
Unless this is a feature request, ALL of the following is required:

- Description of the problem
- Cannot connect to server. Log says Falied to check for newer version when in online mode and loops. Loads fine in offline mode except for using old steam name rather than my new one. I tried going down a version, which you will see in the log. Did not work. The program has been unblocked on my firewall for both incoming and outgoing connections.
- Windows version
- Windows 10
- NMC version
- 1.10.2
- Absolute path to your storage_x.hg files.
- C:\Users\Siven Nitschke\AppData\Roaming\HelloGames\NMS\st_76561198139053932
- Absolute path to your NMS install directory.
- D:\Steam\steamapps\common\No Man's Sky

Use Pastebin of directly attach these files (Users/<Username>/AppData/Roaming/NoMansConnect):

- NMC.log
- https://pastebin.com/CEew9WHW
- settings.json
- https://pastebin.com/JhDSa6bT

If requested, please email your save file to jaszhix@gmail.com. This file will not be used in the game, or on NMC's production server.

- How can this bug be reproduced?
- Not sure. Perhaps fresh install of NMC to a new computer with NMS installed?

**Comment by jaszhix** [comment]
Thanks for bringing this to my attention. The server ran out of disk space during the last backup job, which caused the API to crash. Should be fixed now.
