### ISSUE TITLE
New Computer - Migrating NoMansConnect to machine - email recovery not working

### ISSUE THREAD

**Issue by djehmli** [jaszhix/NoMansConnect#196]
New computer, attempting to move my NoMansConnect data to the new machine.
Using the latest NoMansConnect, it is recognizing my old configuration when starting, but I had a the user name lock on my ID, so it will not load my information.  However, the recovery email does not appear to be functioning.

Looking at the date of last update and the issues list, you may no longer be monitoring this.  But I wanted to let you know what I have found.  Thank you.

**Comment by jaszhix** [comment]
Hi, I've reset protection on the account. The username protection feature misbehaving accounts for a lot of the issues opened, and it will be removed soon.

Sorry for the delay in maintenance lately. While I have taken a break from the game, I do appreciate people's continued interest in the app, and continue to reserve some bandwidth for patching client and API stability issues as they occur.
