### ISSUE TITLE
Stored Locations problems

### ISSUE THREAD

**Issue by BlandSauce** [jaszhix/NoMansConnect#2]
Upgrading to 0.7.0 had some problems, as well as continuing the teleport issue I had in 0.6.1, but a complete clean install of 0.7.0, including removing the user data, has solved that.

Because of that, though, all my stored locations were missing, as well as not recognizing me as the "owner" to edit them if I find them in the recent list.
I did still have previous localstorage files that I was able to place, but when doing so, while it restores my stored location list, and allows the edit menu on my locations, using the editing feature "locks up". (Clicking Update Location does noting, and selecting a different location or Cancel does not remove that box.) Also, new discoveries do not have edit menu.
No errors appear in the log, only initializing and skipping process scan.

I'm thinking the solution may just be "don't do that", but if so, I'd like to know if it's possible to regain my old list and editing control over my old discoveries.

**Comment by jaszhix** [comment]
Can you email me a zip of your LocalStorage and cache.json files? This is definitely a bug.

**Comment by jaszhix** [comment]
@BlandSauce Can you see if this is improved at all in 0.8.0?

**Comment by BlandSauce** [comment]
Any problems mentioned here appear to be fixed.
Editing an existing description starts with empty input boxes, though.

**Comment by jaszhix** [comment]
Great! Yeah, that needs to be fixed. I'll open another issue for it.
