### ISSUE TITLE
Feature request for app with no NMS install

### ISSUE THREAD

**Issue by taukausanake** [jaszhix/NoMansConnect#20]
GitHubs are not normally for feature requests but I figure there's no other place for one and another has made a request sooo...

There are very limited mapping tools out there for NMS, the few if only being Pilgrim Star Path (which doesn't really record, just plots), the Hub Management System (which only does the Galactic Hub area), and No Man's Connect which looks like a full mapping tool. The only problem is I'm a PS4 user and can't use NMC without NMS installed on my computer. Would it be possible to have a version of the program that can run without a MNS install, something that I could upload planet data manually or at least use for mapping purposes? Or is that not possible with the information that is uploaded to the server? Is there a way to use my PS4 save data to run NMC?

**Comment by jaszhix** [comment]
The locations in NMS need a certain amount of data so PC players can teleport. They need coordinates and positional matrices for the player and the ship. To do this in a way that allows just coordinate data, we would need a way to indicate if a location is able to be teleported to. I think its possible, but I'll need to find an elegant way to segregate these two types of locations.

**Comment by taukausanake** [comment]
Maybe just a mapping tool based off this would suffice? The could use the same database for uploaded locations with maybe some parsing for the coordinates, systems only need the center three values I believe. But then I also think the PC version and PS4 version have different servers? I can't remember

**Comment by jaszhix** [comment]
The data from user inputted locations and game detected locations could co-exist, what I am talking about is user experience design, e.g how do we let PC players know they can't teleport to a certain location? Not saying its difficult, but it needs to be done in a certain way to avoid confusion.

**Comment by taukausanake** [comment]
That might be the deal breaker then. I wouldn't want something this specific affect anyone else. Might just be best to keep such programs completely separate then. It's a shame too because this is by far the best in regards to what a mapping tool can be. I'll keep my hopes up though but not if it means messing up anything

**Comment by jaszhix** [comment]
I think what I would do is filter locations created through the app and not the game by default for PC players (let them toggle them on optionally with a no-teleport indicator). PS4 players could see all locations.

**Comment by taukausanake** [comment]
If you can keep two different view settings that could work. I just hope for one day when we get a mapping tool that shows all the information one could want. A complete atlas of the galaxy community run without having to fly across the galaxy to know it's there
