### ISSUE TITLE
Forgot to turn of Username Protection befor reinstalling Windows

### ISSUE THREAD

**Issue by TheGamer20131** [jaszhix/NoMansConnect#22]
- I forgot to turn of the Username Protection and befor reinstalling Windows. And I can´t change the Username or reset the Protection.
- Windows 10
- C:\Users\<Username>\AppData\Roaming\HelloGames\NMS\<Savefolder>
- D:\SteamLibrary\steamapps\common\No Man's Sky

**Comment by jaszhix** [comment]
What username did you use with NMC?

**Comment by TheGamer20131** [comment]
I Used "TheGamer"

**Comment by jaszhix** [comment]
Okay, I unprotected it. You should be able to use it again.

**Comment by TheGamer20131** [comment]
Ok it worked. Thank You

**Comment by jaszhix** [comment]
You're welcome.
