### ISSUE TITLE
[Scrolling remote locations] List jumps to top

### ISSUE THREAD

**Issue by ukmerlin** [jaszhix/NoMansConnect#29]
When scrolling to the bottom of a list, it will immediately jump back to the top of the list.
Reproduce by setting a short list filter like "bases" and "PC" only.
Scroll to bottom of list.

**Comment by jaszhix** [comment]
This is intentional because the scrolling used to be in a worse state than it is now so it can probably benefit from some adjustment. Try Load 60 More Locations in the menu.

**Comment by ukmerlin** [comment]
Loading 60 more somehow keeps the same locations at the bottom so they must be loading from the top. This means that if you want one or two of them from the bottom of the list it will not stay long enough to be selected. As the 60 more are loading I do see the slider change size so they are loading. Also, if you load 60 more a couple of time the map will crush after about four of five add on loads.

**Comment by jaszhix** [comment]
They are loading from the bottom, what you're noticing is the effect of old code handling the scroll event listener that needs to be cleaned up. It's a list and it gets reordered by your filters on every load so sometimes locations don't move but they're just getting resorted. Honestly I don't think it's practical to scroll a list with thousands of things on it anyway so it doesn't seem like it would be the first thing I fix as far as usability goes.

**Comment by jaszhix** [comment]
Still haven't reproduced this one, I'm going to mark it as resolved.
