### ISSUE TITLE
Screenshots and dual monitors

### ISSUE THREAD

**Issue by ianm32** [jaszhix/NoMansConnect#3]
Hi,

I play NMS in borderless windowed mode, and I have two monitors.  The second only gets used for specific purposes.  The screenshots that NoMansConnect automatically captures seem to split the difference between my two screens, resulting in a very disjointed image.  An example is attached; the top half is the wallpaper for my second screen, with some black space since the display resolution is much lower than my primary display.

![nmslocation-ian the great-1461--8-950-0-76-2-21720f95-b125-41b6-b9ba-571f9912fdc8](https://cloud.githubusercontent.com/assets/27756065/25163034/bcc06bc8-248c-11e7-8d9d-133029f25628.jpg)

**Comment by jaszhix** [comment]
Ah, yeah I have noticed this. Currently auto capturing is broken on multiple monitor configurations. I do want to get it working to capture only the primary monitor, and available in full screen mode as well. For now though, your best bet is to disable this until I can implement it a better way.

**Comment by jaszhix** [comment]
Fixed in 0.11.0.
