### ISSUE TITLE
Maximizing/un-maximizing the window collapses the app window into a tiny square

### ISSUE THREAD

**Issue by jaszhix** [jaszhix/NoMansConnect#31]

**Comment by PabloStrange** [comment]
How is the status here? 

When i connect to my gaming pc via remotedesktop on my smartphone NMC crumbles into a halfsized window without any options to restore. rebooting the pc won't help. only reinstalling helps

**Comment by taukausanake** [comment]
My windows withdrew into the tiny box but I managed to get it resized. It wasn't too hard but still a bug all the same. Just mess with the box a bit and you'll grab one of the edges or corner to resize it

**Comment by jaszhix** [comment]
I don't really think there's anything else to add. I can fix it when I have time, but currently I don't.

**Comment by PabloStrange** [comment]
@jaszhix take your time man
