### ISSUE TITLE
Multiple instances of NMC

### ISSUE THREAD

**Issue by temp-999** [jaszhix/NoMansConnect#32]
Reproducible: Start up NMC. Reduce window. Start up NMC (asks for a username). 

Played around with it a bit by opening the app twice and then closing them. At some point NMC started asking for a username during the first execution. So I entered it and NMC reset as though I was a first time user. Lost all my Stored Locations (only had two) except for the current one and Offline Mode was flipped to Off.

NMC.log:  https://pastebin.com/dG1ReU91

I don't know where username Explorer came from. When asked after the fresh install yesterday, I had entered temp.

**Comment by jaszhix** [comment]
Why would the user need to run two instances of the app? I never designed it to.
