### ISSUE TITLE
Save mixup/confusion

### ISSUE THREAD

**Issue by GmrLeon** [jaszhix/NoMansConnect#34]
Unfortunately, I've not come across this myself, but there are user reports from the current version of their teleport destinations and progress being jumbled up upon teleport. It's unclear why, but when selecting a destination to teleport, it's taking users to a different place and giving them different inventory and discovery contents. 

"It's as if I've received another user's save," is the simplest way I've seen it described. Perhaps there's an issue in how NMC is pulling the save data, occasionally grabbing entire saves and overwriting users' saves with others users' in the process of attempting to teleport them? 

Sorry I can't give much more detail than that, but I hope it might help direct your attention to it!

**Comment by jaszhix** [comment]
#26
