### ISSUE TITLE
Add a username recovery feature, consider using password/email associations

### ISSUE THREAD

**Issue by jaszhix** [jaszhix/NoMansConnect#36]

**Comment by MickCasanova** [comment]
Here's my latest log file as requested. As you can see, my user name appears as "Explorer". No matter what I do, I can't log in.
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/1878436/NMC.log)

**Comment by jaszhix** [comment]
@MickCasanova I think I reproduced the username recovery bug. Can you test this version? http://www.mediafire.com/file/69t9u2pacy52pal/NMC102-recovery-fix.exe

**Comment by MickCasanova** [comment]
I did a complete uninstall, and reinstalled the new one, and still cannot get in.

**Comment by jaszhix** [comment]
Did you see the email recovery prompt? If not, try changing your username to MickCasanova in the settings.json file, or click Override Username in the app.

**Comment by MickCasanova** [comment]
I've never seen an email recovery prompt, and haven't with this one either. On that notion, I attempted to set the recovery email and got an error. I edited the setting.json and entered my name manually, and that didn't help. Still not able to login. It reloads and displays the user name as "Explorer".

As a side note, it gives me a list of locations at startup. This never seemed to happen before. At least something is working for me. :)

**Comment by jaszhix** [comment]
Cool, maybe getting closer. Can you zip up `C:\Users\YourUser\AppData\Roaming\NoMansConnect` and email it to me (jaszhix@gmail.com)? That will make it easier to reproduce.

**Comment by jaszhix** [comment]
As discussed via email, this was caused by a server bug which is now patched. The API method was checking the username first, and the machine ID as a fail-safe - but if "Explorer" is sent to the server then the generic (reserved) profile is returned. This was a problem for GOG users, who have to override their username because their save data always uses "Explorer" as the username.

**Comment by MickCasanova** [comment]
Thank you for resolving this issue. I can't tell you how much I appreciate it. NMC is an app that I have come to rely on for truly enjoying NMS. Without it, the game is not nearly as interesting to me.
