### ISSUE TITLE
Save file not being modified

### ISSUE THREAD

**Issue by toddumptious** [jaszhix/NoMansConnect#39]
Issue template for bug reports:

- At first I thought restoring my base to a new location was just broken, but I tested adding money to my save file and that does not work either.
- Windows 10 home
- C:\Users\New User\AppData\Roaming\HelloGames\NMS\st_76561197997417034
- C:\Program Files (x86)\Steam\steamapps\common

Use Pastebin or a small snippet relevant to the issue and include these files from Roaming/AppData/NoMansConnect:
- NMC.log
https://pastebin.com/wb5Kxn9i

- settings.json
https://pastebin.com/7Md2CJFJ

- How can this bug be reproduced?

**Comment by toddumptious** [comment]
I have changed my name to toddumptious on steam but my discoveries are logged as christianhour on NMC (my old steam name), would this be causing issues? Just thought was worth mentioning also.

**Comment by toddumptious** [comment]
Further issues have been encountered. 

I thoguht maybe changing my name to my new steam name would fix things. So I turned off username protection and changed it. However all my discoveries disappeared and I noticed in the recent discoveries column, my new name was appearing for discoveries I did not make, using mods I've never had, so I switched back to my old name to see if it would restore things but it did not. 

On top of this there are no longer any saved bases for me to restore. It seems like NMC just wiped itself clean when I unprotected my name and then changed it.

What did I do wrong? It feels like I did it exactly as directed.

**Comment by toddumptious** [comment]
I uninstalled and reinstalled NMC, set my username to the original "christianhour".

Despite this it restarted as explorer. On the galactic map, since its loading my most recent save file location as a discovery, i can see my previous discoveries. They are now showing up on the 3d map with the new name I had set "ToddUmptious" (which I never set protection on) so I switched to this, and again NMC restarted with the name "explorer". No matter what I do it constantly resets  to explorer.

It seems in trying to solve the issue myself I've just made things worse and worse. Its a shame, I was enjoying charting my discoveries with screenshots as I went along, plaing without it feels strange so I'll wait until we can figure this out before I play again :) I know I should be able to restore my discoveries locally with the pastebin I shared in first post but I will wait until instructions from your goodself just in case I make things even worse haha.

**Comment by toddumptious** [comment]
I managed to fix my lost discoveries by changing username back to Toddumptious after another reinstall. Still have lost base save and cannot modify save file, will toy around with pastebin data to see if i can recover stored base anyway

**Comment by jaszhix** [comment]
Provided its not protected, switching back to the username in you had before these events occurring, by editing settings.json, should sync you back up with the server. Just make sure you are done editing settings.json and close whatever app you used to edit it before relaunching NMC.

It looks like there may be a bug with spaces in the save file path. 

```
 "Command failed: .\\nmssavetool\\nmssavetool.exe encrypt -g normal -i .\\nmssavetool\\saveCache.json -s C:\\Users\\New User\\AppData\\Roaming\\HelloGames\\NMS\\st_76561197997417034\nError locating game save file:\nCould not find a part of the path 'C:\\Users\\New'
```

**Comment by toddumptious** [comment]
If I edit the path in settings with %20 will it fix the issue do you think? BTW are you taking part in the ARG? I;m same name on ETARC and the Discords ;)

**Comment by jaszhix** [comment]
I don't know, you could try it.

I've been observing the game from a distance, but I don't have a lot of time to engage in it.

**Comment by laughingearth** [comment]
It looks like I might be having the same issue.  From the log file:
"Command failed: .\\nmssavetool\\nmssavetool.exe encrypt -g normal -i .\\nmssavetool\\saveCache.json -s C:\\Users\\The Laughing Earth\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198049596904\nError locating game save file:\nCould not find a part of the path 'C:\\Users\\The'.\r\n"

My NMS installation is on a separate game drive (F).  The save file directory I've specified is here:
C:\Users\The Laughing Earth\AppData\Roaming\HelloGames\NMS\st_76561198049596904

The install directory is here:
F:\Steam\steamapps\common\No Man's Sky

Also having the issue with my default name as "Explorer" - getting the "must disable username protection" message when I try to change it.

Sorry to be a pain, but your guidance would be helpful.  :-)

**Comment by jaszhix** [comment]
You can't have spaces in your file path, like I mention in this very thread.
