### ISSUE TITLE
Teleporting into space with no ship

### ISSUE THREAD

**Issue by XavierGray** [jaszhix/NoMansConnect#40]
when i try to teleport certain locations, i get teleported into space with no ship, even though ALL of the locations are suppose to be space stations. This happens with different locations, but basically, once it teleports me into space, everytime i try to teleport to that location, the same thing happens.

Windows version: WIndows 7 Pro
C:\Users\Xavier\AppData\Roaming\HelloGames\NMS\st_76561198178964862

C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky

NMC.log
Thu Jul 20 2017 11:54:09 GMT-0500 (Central Daylight Time):    "Initializing No Man's Connect 0.14.0"
Thu Jul 20 2017 11:54:09 GMT-0500 (Central Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Thu Jul 20 2017 11:54:09 GMT-0500 (Central Daylight Time):    "Skipping process scan..."
Thu Jul 20 2017 11:54:10 GMT-0500 (Central Daylight Time):    "Username: XavierGray"
Thu Jul 20 2017 11:54:10 GMT-0500 (Central Daylight Time):    "Active save file: C:\\Users\\Xavier\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198178964862\\storage2.hg"
Thu Jul 20 2017 11:54:10 GMT-0500 (Central Daylight Time):    "Current location: -1542:0:-765:0:42:0"
Thu Jul 20 2017 11:55:21 GMT-0500 (Central Daylight Time):    "Skipping process scan..."
Thu Jul 20 2017 11:55:36 GMT-0500 (Central Daylight Time):    "Skipping process scan..."

Even though it says it can't find the install path, clicking on NMS Install directory in settings, opens the correct path

[settings - Copy.txt](https://github.com/jaszhix/NoMansConnect/files/1163180/settings.-.Copy.txt)

- How can this bug be reproduced?

Perhaps try teleporting to the most recent location where i have this issue.
Galactic address:  01F9:007F:0502:002A
Voxel Address: -1542:0:-765:0:42:0

**Comment by jaszhix** [comment]
Are you using mods? If you switch from a mod that modifies the voxel generation, then teleport to it without that mod, it will strand you unless you're lucky and land on a planet. There is a way to query people's mods, but so far it seems it never works for Windows 7 users, which is probably related to the install directory issue.

**Comment by XavierGray** [comment]
Hi Jason

Thanks for your response. I should have mentioned this in my original post. I am not using any mods at all. My NMS is completely vanilla. The only things i've ever used, was the NMS location manager, and the NMS save editor.
NMS location manager doesn't work with pathfinder update, and NMSSE is out -of-date and i haven't tried to use it either.

Thanks
Jeff
--------------------------------------------
On Mon, 7/24/17, Jason Hicks <notifications@github.com> wrote:

 Subject: Re: [jaszhix/NoMansConnect] Teleporting into space with no ship (#40)
 To: "jaszhix/NoMansConnect" <NoMansConnect@noreply.github.com>
 Cc: "XavierGray" <xgraystorm01@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Monday, July 24, 2017, 9:32 PM
 
 Are you using mods? If you switch
 from a mod that modifies the voxel generation, then teleport
 to it without that mod, it will strand you unless you're
 lucky and land on a planet. There is a way to query
 people's mods, but so far it seems it never works for
 Windows 7 users, which is probably related to the install
 directory issue.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by jaszhix** [comment]
Is this still a problem for you? Please try 0.16.0. By the way, if a location is blue, it is not guaranteed to work because it is manually entered by address.

**Comment by jaszhix** [comment]
Closing since no follow up was received.
