### ISSUE TITLE
Teleport doesn't work and changes my save

### ISSUE THREAD

**Issue by taukausanake** [jaszhix/NoMansConnect#41]
- Description of the problem
Whenever I try to use the teleport feature in NMC I keep getting sent to the same system. What more it changes my save to the same thing each time. I've tried this multiple times in my Creative save even deleting it. Also happens in Normal mode save. I reinstalled NMC on my machine and still get the same issue.

- Windows version
Windows 10 x64
NMC 0.14.0

- Absolute path to your storage_x.hg files.
C:\Users\me\AppData\Roaming\HelloGames\NMS\st_76561198043762175

- Absolute path to your NMS install directory.
C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky

- NMC.log
https://pastebin.com/7aC5ZB85

- settings.json
https://pastebin.com/d574vQ6X

**Comment by jaszhix** [comment]
This one's pretty easy, the app doesn't have write access to its own resources. 

```
Thu Aug 03 2017 17:04:05 GMT-0500 (Central Daylight Time):    {"errno":-4048,"code":"EPERM","syscall":"open","path":"C:\\Program Files\\NoMansConnect\\nmssavetool\\saveCache.json"}
```

You need to run it as an administrator, or install it for just your user.

**Comment by taukausanake** [comment]
Alright, run as admin works. Thanks!
