### ISSUE TITLE
[Check MODS directory before reading it] installed it and sits on the NMS loading screen in the NMC app

### ISSUE THREAD

**Issue by naturalphenomenon** [jaszhix/NoMansConnect#42]
Installed it and it does nothing but sit on the NMC loading screen. Tried restarting it and reset remote cache
installed new java and dont know why it wont work
- Windows version - windows 10
- Absolute path to your storage_x.hg files. 
- Absolute path to your NMS install directory.

**Comment by jaszhix** [comment]
NMC does _not_ use java at all. Please follow the instructions in the issue template and give me _all_ the information I ask for.

**Comment by naturalphenomenon** [comment]
Ok writing it up now. Give me 10-20 min I have done afew things to fix this but nothing works. check back soon because this will  fix my broken quests if i get this program working

**Comment by naturalphenomenon** [comment]
I fixed it i didnt have Steam\\steamapps\\common\\No Man's Sky\\GAMEDATA\\PCBANKS\\MODS made



Issue template for bug reports:

- Description of the problem
When installing it i get this i have run it as administrator and not administrator
http://imgur.com/a/MOp2C
Then once it loads it stays at
http://imgur.com/a/3lt6b 

- Windows version
Windows 10 64Bit Pro

- Absolute path to your storage_x.hg files.
C:\Users\Natural Phenomenon\AppData\Roaming\HelloGames\NMS\st_76561197999922327
- Absolute path to your NMS install directory.
G:\steam\SteamApps\common\No Man's Sky
Use Pastebin or a small snippet relevant to the issue and include these files from Roaming/AppData/NoMansConnect:
- NMC.log
Sun Aug 13 2017 15:46:13 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.15.1"
Sun Aug 13 2017 15:46:13 GMT-0400 (Eastern Daylight Time):    "Failed to read mods directory: Error: ENOENT: no such file or directory, scandir 'G:\\Steam\\steamapps\\common\\No Man's Sky\\GAMEDATA\\PCBANKS\\MODS'"

- settings.json
{"maximized":false,"maintenanceTS":1502653573248,"wallpaper":null,"installDirectory":null,"saveDirectory":"C:\\Users\\Natural Phenomenon\\AppData\\Roaming\\HelloGames\\NMS","username":"Explorer","mapLines":false,"map3d":false,"mapDrawDistance":false,"show":{"Shared":true,"PS4":true,"Explored":true,"Center":true,"Favorite":true,"Current":true,"Selected":true,"Base":true},"filterOthers":false,"useGAFormat":false,"remoteLocationsColumns":1,"sortStoredByTime":false,"pollRate":60000,"mode":"normal","storedBases":[],"storedLocations":[],"favorites":[],"autoCapture":false,"ps4User":false,"compactRemote":false,"offline":false,"showOnlyNames":false,"showOnlyDesc":false,"showOnlyScreenshots":false,"showOnlyGalaxy":false,"showOnlyBases":false,"showOnlyPC":false,"showOnlyCompatible":false,"sortByDistance":false,"sortByModded":false}

- How can this bug be reproduced?
Installing the app

**Comment by naturalphenomenon** [comment]
Update it is rewriting my saves completly, Luckily i backed up everything. Its teleporting me to a star station with someone eleses set up with the atlas path update screen

**Comment by taukausanake** [comment]
@naturalphenomenon I had the same problem. You have to run the program as administrator as per [here](https://github.com/jaszhix/NoMansConnect/issues/41#issuecomment-320108121)

Out of curiosity, can you give a general list of what gets changed in it? Like the type and style of your ship, multi-tool, and planet you end up on?

**Comment by naturalphenomenon** [comment]
It gave me a one of the eletronic races ships, a 26 slot freighter and 46 mil

**Comment by taukausanake** [comment]
@naturalphenomenon was it a silvery explorer with two boosters on it and max slots?

**Comment by jaszhix** [comment]
Fixed in 0.16.0
