### ISSUE TITLE
Add ability to delete from the Stored Locations?

### ISSUE THREAD

**Issue by temp-999** [jaszhix/NoMansConnect#43]
The only way that I've found to delete entries from the Stored Locations is to modify the settings.json file. It would be nice if the ... for each entry would also permit deletion. This would only affect the Stored Locations area and not anything stored on the server.

- Windows version 10 Pro 1607
- Absolute path to your storage_x.hg files. N/A
- Absolute path to your NMS install directory. N/A

- NMC.log N/A
- settings.json N/A

- How can this bug be reproduced? Not a bug.

**Comment by jaszhix** [comment]
You can delete other people's locations from the stored list, but doing so for your own is not something I've had in mind because everything is set up to automatically sync.

**Comment by jaszhix** [comment]
You can now hide stored locations and toggle the hide filter. These changes only take place locally though.
