### ISSUE TITLE
Crash dump produced on exit

### ISSUE THREAD

**Issue by temp-999** [jaszhix/NoMansConnect#44]
- Description of the problem: When I exit NMC a crash dump is produced at C:\Users\<me>\AppData\Local\CrashDumps. No other indication of an error is produced.
NoMansConnect.exe.1460.dmp   8/14/2017 8:10 PM   3,897 KB
NoMansConnect.exe.9996.dmp   8/14/2017 8:10 PM   3,896 KB

- Windows version: 10 PRO 1607
- Absolute path to your storage_x.hg files: C:\Users\<me>\AppData\Roaming\HelloGames\NMS\st_###################
- Absolute path to your NMS install directory: D:\SteamLibrary\SteamApps\common\No Man's Sky

Use Pastebin or a small snippet relevant to the issue and include these files from Roaming/AppData/NoMansConnect:
- NMC.log:
Mon Aug 14 2017 20:09:54 GMT-0700 (Pacific Daylight Time):    "Finished reading No Man's Sky v4102 save file."
Mon Aug 14 2017 20:10:08 GMT-0700 (Pacific Daylight Time):    "Finished reading No Man's Sky v4102 save file."
Mon Aug 14 2017 20:10:40 GMT-0700 (Pacific Daylight Time):    "Initializing No Man's Connect 0.15.1"
Mon Aug 14 2017 20:10:40 GMT-0700 (Pacific Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Mon Aug 14 2017 20:10:41 GMT-0700 (Pacific Daylight Time):    "Finished reading No Man's Sky v4102 save file."
Mon Aug 14 2017 20:10:41 GMT-0700 (Pacific Daylight Time):    "Active save file: C:\\Users\\<me>\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198053233295\\storage.hg"
Mon Aug 14 2017 20:10:41 GMT-0700 (Pacific Daylight Time):    "Username: temp"
Mon Aug 14 2017 20:10:41 GMT-0700 (Pacific Daylight Time):    "Current location: -939:-17:698:0:121:1"

- settings.json: Will email if necessary.

- How can this bug be reproduced? On my PC by exiting NMC.

**Comment by jaszhix** [comment]
After looking, I'm seeing dump files as well. 

![screenshot from 2017-08-15 01-04-50](https://user-images.githubusercontent.com/6859057/29303939-ea5b38f8-8155-11e7-89c5-d78628d7e6e3.png)

NMC uses secondary threads to handle writing files to JSON and making web requests, and since these are asynchronous its possible they're still doing their thing after the main thread exits. I'll try to look into it.

**Comment by temp-999** [comment]
I don't know if it matters but I went from Windows 10 pro 1607 to 1703 today. NMC still crashes on exit but the dump isn't in ...\AppData\Local\CrashDumps anymore.  

From Control Panel\All Control Panel Items\Security and Maintenance\Problem Details:

Source
NoMansConnect

Summary
Stopped working

Date
‎9/‎6/‎2017 3:58 PM

Status
Report sent

Description
Faulting Application Path:	C:\Program Files\NoMansConnect\NoMansConnect.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	NoMansConnect.exe
Application Version:	0.17.0.0
Application Timestamp:	596d1933
Fault Module Name:	ntdll.dll
Fault Module Version:	10.0.15063.447
Fault Module Timestamp:	a329d3a8
Exception Code:	c0000005
Exception Offset:	0000000000030e01
OS Version:	10.0.15063.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	b67c
Additional Information 2:	b67c66ff874185cabe32e45d2dd2e408
Additional Information 3:	111a
Additional Information 4:	111afaa94de91b6ac29e731f658b68c9

Extra information about the problem
Bucket ID:	4554cf468f0ce02ae94433d2ed147bdf (120817622200)

**Comment by jaszhix** [comment]
Yes, it looks like a bug that would be hard for me to fix, because I'm not about to fire up a compiler with debug symbols to figure out which node module is causing this to happen in Win32. I'm closing this for now since its unlikely to be fixed by me, unless upstream sorts itself out.
