### ISSUE TITLE
Username is locked

### ISSUE THREAD

**Issue by skulumani** [jaszhix/NoMansConnect#45]
Issue template for bug reports:

- Account/Username is protected
- Running on Linux Xubuntu 16.04
- `/usr/bin/local/nomansconnect`

I'm trying to run your app on a different computer than where No Man's Sky is installed. I just wanted to log my location and check out how it works. 

It claims my username is protected. The username is shanks.k. 

Does this username need to match Steam/PS4 or some other website?

**Comment by jaszhix** [comment]
By default if you don't specify one, it uses the Steam username found in your save file. shanks.k doesn't seem to pull up anything on the server.

**Comment by jaszhix** [comment]
Closing since no follow up was received.
