### ISSUE TITLE
Loaded Into Another Player's Save Instead of Teleporting

### ISSUE THREAD

**Issue by DiabetikGam3r** [jaszhix/NoMansConnect#46]
Issue template for bug reports:

- Description of the problem
I placed in an address and realized the first 5 letters didn't need to be included. Took those out. I was trying to check out a planet a friend had shared the address of. I teleported to a different system and ended up loading another player's save. 
And now I can't teleport to any coordinates.
- Windows version
1703
- Absolute path to your storage_x.hg files.
C:\Users\akane\AppData\Roaming\HelloGames\NMS\st_76561198029450672
- Absolute path to your NMS install directory.
C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky\Binaries

Use Pastebin or a small snippet relevant to the issue and include these files from Roaming/AppData/NoMansConnect:
- NMC.log
https://pastebin.com/zEM0SeDw
- settings.json
Not sure how to share that to be honest... This is my first time reporting a bug. Try this?:
https://drive.google.com/open?id=0B6EnXlSvQD9pT3VQM0NWdTdIQnM

- How can this bug be reproduced?
Not sure. Try teleporting to the address? 0BDB:0081:0226:007A

**Comment by jaszhix** [comment]
> {"errno":-4048,"code":"EPERM","syscall":"open","path":"C:\\Program Files\\NoMansConnect\\nmssavetool\\saveCache.json"}

You need to run it as administrator.

**Comment by jaszhix** [comment]
https://github.com/jaszhix/NoMansConnect/issues/41

**Comment by DiabetikGam3r** [comment]
Thanks @jaszhix 
This worked for me. Weird that I've never had to do that before. Good to know! You've saved me so much time, it's unbelievable. :)

**Comment by jaszhix** [comment]
No problem, glad it works for you.
