### ISSUE TITLE
Can't locate PC Data

### ISSUE THREAD

**Issue by ivXtreme** [jaszhix/NoMansConnect#47]
Running Windows 10 x64 latest update.

When I start the program, it says "Save Data Not Found.  Select PS4 to skip this step...".  I pick the NMS folder location ""C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky", but the program then restarts and then says "Save Data Not Found.  Select PS4 to skip this step..." once again.  I have also tried using "C:\Users\Ivan\AppData\Roaming\HelloGames\" but still doesn't work.

I installed and I run the program as an administrator.  When installing the program, I did get a javascript error which may or may not have anything to do with the issue.  I have attached a picture of the javascript error message I get when initially installing.

![capture](https://user-images.githubusercontent.com/20237148/29450252-8ddc07f4-83c3-11e7-8776-8ba482a5ea41.PNG)

Attached are the NMS and settings file:
[Desktop.zip](https://github.com/jaszhix/NoMansConnect/files/1233759/Desktop.zip)

**Comment by jaszhix** [comment]
Did you install it for just your user or all users?

**Comment by ivXtreme** [comment]
I installed it only for me, then I have tried installing it for all users.  Same issue.

**Comment by jaszhix** [comment]
https://github.com/jaszhix/NoMansConnect/issues/30
