### ISSUE TITLE
Username Explorer is protected on fresh install when trying to use for PS4 user

### ISSUE THREAD

**Issue by bansama** [jaszhix/NoMansConnect#48]
Tried to use No Man's Connect for a PS4 play through but get the protected username prompt for Explorer. Have set my actual PS4 user name, but that changes nothing. No Man's Connect is not connected to a Steam install and this error occurs as soon as PS4 is selected when prompted for system you're playing on.

OS is Windows 7
No Man's Connect is not linked to any local saves as this is to play on PS4.

[NMC_log.txt](https://github.com/jaszhix/NoMansConnect/files/1236391/NMC_log.txt)

[settings_json.txt](https://github.com/jaszhix/NoMansConnect/files/1236393/settings_json.txt)

**Comment by jaszhix** [comment]
> "status":403,"statusText":"Forbidden"

Do you have any anti-malware software installed that could be blocking the connection?

**Comment by bansama** [comment]
None. The exact same build of No Man's Connect also works on the same PC when set to be used with my Steam install. It's only the PS4 function that doesn't work. At first I thought it was because I was already using it with Steam, but having tried a complete fresh install of NMC this has proven to not be the case.

**Comment by jaszhix** [comment]
When I look up your profile by machine ID, it shows the username as bansama. This is looking like a server-side bug. Maybe see if you can authenticate in PC mode, then switch to PS4.

**Comment by bansama** [comment]
Tried that. But the NMC app relaunches when switching between platforms and throws up the Protection enabled for Explorer prompt again. This also true for V 0.17.0.

**Comment by jaszhix** [comment]
Right, issue is on the server.
