### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by Flandyn** [jaszhix/NoMansConnect#49]
- Description of the problem
There are no build instructions.

- How can this bug be reproduced? 
Not a bug.

**Comment by taukausanake** [comment]
I mean if you want to build the code I guess instructions would be nice. If you are looking to use the app then you go to releases and download that. Is there a reason someone would want to build from source? Maybe make a branch?

**Comment by jaszhix** [comment]
If you're familiar with developing web apps with NPM its pretty straight forward.

- Install [yarn](https://yarnpkg.com/en/docs/install)
- Run ```yarn``` in the root directory
- Run ```npm run dev```
