### ISSUE TITLE
IamIsbuck

### ISSUE THREAD

**Issue by IamIsbuck** [jaszhix/NoMansConnect#54]
Windows 10 64. All updates applied. NMS v1.35, exp1.36

Under Options-Add Units. Adding units results in me being relocated to a system the other side of the Galaxy and my most recent save being replaced by someone else's save. tested on v1.35 and exp1.36. Tested with both one of my existing saves and with brand new save (just the 1st ship interaction then exit ship to save and quit the game). The save file that I am given is always the same and appears to belong to a player called neuropuff.

File locations:-
C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky
C:\Users\Ian\AppData\Roaming\HelloGames\NMS\st_76561198321576578

Roaming/AppData/NoMansConnect:
- NMC.log

I carried out all testing today (11/09/2017). Here Follows a snippet from NMC.log
----------------------------

Thu Sep 07 2017 10:45:46 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Fri Sep 08 2017 09:53:01 GMT+0100 (GMT Daylight Time):    "Initializing No Man's Connect 0.17.0"
Fri Sep 08 2017 09:53:15 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Fri Sep 08 2017 09:53:15 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Fri Sep 08 2017 09:53:15 GMT+0100 (GMT Daylight Time):    "Current location: 774:-2:-1618:0:171:2"
Fri Sep 08 2017 09:53:15 GMT+0100 (GMT Daylight Time):    "Active save file: C:\\Users\\Ian\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198321576578\\storage2.hg"
Fri Sep 08 2017 13:02:48 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 13:05:51 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:26:41 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:27:42 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:28:43 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:29:44 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:30:45 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:31:46 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:32:47 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:33:48 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:34:49 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:35:50 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:36:51 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:37:52 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:38:53 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:39:54 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:40:55 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Fri Sep 08 2017 17:41:56 GMT+0100 (GMT Daylight Time):    "AJAX Worker failure: pollRemoteLocations"
Mon Sep 11 2017 14:45:37 GMT+0100 (GMT Daylight Time):    "Initializing No Man's Connect 0.17.0"
Mon Sep 11 2017 14:45:41 GMT+0100 (GMT Daylight Time):    "Newer version of NMC found."
Mon Sep 11 2017 14:45:50 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 14:45:50 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Mon Sep 11 2017 14:45:50 GMT+0100 (GMT Daylight Time):    "Current location: 774:-2:-1618:0:239:2"
Mon Sep 11 2017 14:45:50 GMT+0100 (GMT Daylight Time):    "Active save file: C:\\Users\\Ian\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198321576578\\storage3.hg"
Mon Sep 11 2017 14:50:43 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 14:50:58 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 14:52:42 GMT+0100 (GMT Daylight Time):    "Initializing No Man's Connect 0.17.0"
Mon Sep 11 2017 14:52:44 GMT+0100 (GMT Daylight Time):    "Newer version of NMC found."
Mon Sep 11 2017 14:52:45 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 14:52:45 GMT+0100 (GMT Daylight Time):    "Active save file: C:\\Users\\Ian\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198321576578\\storage3.hg"
Mon Sep 11 2017 14:52:45 GMT+0100 (GMT Daylight Time):    "Current location: 774:-2:-1618:0:239:2"
Mon Sep 11 2017 14:52:45 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Mon Sep 11 2017 14:53:46 GMT+0100 (GMT Daylight Time):    "Initializing No Man's Connect 0.17.0"
Mon Sep 11 2017 14:53:48 GMT+0100 (GMT Daylight Time):    "Newer version of NMC found."
Mon Sep 11 2017 14:53:48 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 14:53:48 GMT+0100 (GMT Daylight Time):    "Active save file: C:\\Users\\Ian\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198321576578\\storage3.hg"
Mon Sep 11 2017 14:53:48 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Mon Sep 11 2017 14:53:48 GMT+0100 (GMT Daylight Time):    "Current location: 774:-2:-1618:0:239:2"
Mon Sep 11 2017 14:55:47 GMT+0100 (GMT Daylight Time):    "Initializing No Man's Connect 0.17.1"
Mon Sep 11 2017 14:55:50 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 14:55:50 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Mon Sep 11 2017 14:55:50 GMT+0100 (GMT Daylight Time):    "Active save file: C:\\Users\\Ian\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198321576578\\storage3.hg"
Mon Sep 11 2017 14:55:50 GMT+0100 (GMT Daylight Time):    "Current location: 774:-2:-1618:0:239:2"
Mon Sep 11 2017 15:11:54 GMT+0100 (GMT Daylight Time):    "Initializing No Man's Connect 0.17.1"
Mon Sep 11 2017 15:11:59 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 15:11:59 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Mon Sep 11 2017 15:11:59 GMT+0100 (GMT Daylight Time):    "Active save file: C:\\Users\\Ian\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198321576578\\storage3.hg"
Mon Sep 11 2017 15:11:59 GMT+0100 (GMT Daylight Time):    "Current location: 774:-2:-1618:0:239:2"
Mon Sep 11 2017 15:12:17 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 15:12:32 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 15:28:26 GMT+0100 (GMT Daylight Time):    "Initializing No Man's Connect 0.17.1"
Mon Sep 11 2017 15:28:29 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 15:28:29 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Mon Sep 11 2017 15:28:29 GMT+0100 (GMT Daylight Time):    "Current location: 774:-2:-1618:0:239:2"
Mon Sep 11 2017 15:28:29 GMT+0100 (GMT Daylight Time):    "Active save file: C:\\Users\\Ian\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198321576578\\storage3.hg"
Mon Sep 11 2017 15:31:59 GMT+0100 (GMT Daylight Time):    "Initializing No Man's Connect 0.17.1"
Mon Sep 11 2017 15:32:02 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 15:32:02 GMT+0100 (GMT Daylight Time):    "Active save file: C:\\Users\\Ian\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198321576578\\storage3.hg"
Mon Sep 11 2017 15:32:02 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Mon Sep 11 2017 15:32:02 GMT+0100 (GMT Daylight Time):    "Current location: 774:-2:-1618:0:239:2"
Mon Sep 11 2017 15:34:08 GMT+0100 (GMT Daylight Time):    "Initializing No Man's Connect 0.17.1"
Mon Sep 11 2017 15:34:12 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 15:34:12 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Mon Sep 11 2017 15:34:12 GMT+0100 (GMT Daylight Time):    "Active save file: C:\\Users\\Ian\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198321576578\\storage3.hg"
Mon Sep 11 2017 15:34:12 GMT+0100 (GMT Daylight Time):    "Current location: 774:-2:-1618:0:239:2"
Mon Sep 11 2017 15:35:37 GMT+0100 (GMT Daylight Time):    {"errno":-4048,"code":"EPERM","syscall":"open","path":"C:\\Program Files\\NoMansConnect\\nmssavetool\\saveCache.json"}
Mon Sep 11 2017 15:35:45 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4101 save file."
Mon Sep 11 2017 15:36:00 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4101 save file."
Mon Sep 11 2017 15:48:19 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 15:48:22 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 15:52:26 GMT+0100 (GMT Daylight Time):    {"errno":-4048,"code":"EPERM","syscall":"open","path":"C:\\Program Files\\NoMansConnect\\nmssavetool\\saveCache.json"}
Mon Sep 11 2017 15:52:32 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4101 save file."
Mon Sep 11 2017 15:52:46 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4101 save file."
Mon Sep 11 2017 15:53:05 GMT+0100 (GMT Daylight Time):    "Initializing No Man's Connect 0.17.1"
Mon Sep 11 2017 15:53:08 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4101 save file."
Mon Sep 11 2017 15:53:08 GMT+0100 (GMT Daylight Time):    "Active save file: C:\\Users\\Ian\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198321576578\\storage.hg"
Mon Sep 11 2017 15:53:08 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Mon Sep 11 2017 15:53:08 GMT+0100 (GMT Daylight Time):    "Current location: -918:2:1391:0:78:0"
Mon Sep 11 2017 16:53:10 GMT+0100 (GMT Daylight Time):    "Initializing No Man's Connect 0.17.1"
Mon Sep 11 2017 16:53:14 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 16:53:14 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Mon Sep 11 2017 16:53:14 GMT+0100 (GMT Daylight Time):    "Active save file: C:\\Users\\Ian\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198321576578\\storage.hg"
Mon Sep 11 2017 16:53:14 GMT+0100 (GMT Daylight Time):    "Current location: 1066:6:1399:0:1:1"
Mon Sep 11 2017 16:54:02 GMT+0100 (GMT Daylight Time):    "Initializing No Man's Connect 0.17.1"
Mon Sep 11 2017 16:54:04 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Mon Sep 11 2017 16:54:04 GMT+0100 (GMT Daylight Time):    "Active save file: C:\\Users\\Ian\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198321576578\\storage.hg"
Mon Sep 11 2017 16:54:04 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Mon Sep 11 2017 16:54:04 GMT+0100 (GMT Daylight Time):    "Current location: 1066:6:1399:0:1:1"
Mon Sep 11 2017 16:54:18 GMT+0100 (GMT Daylight Time):    {"errno":-4048,"code":"EPERM","syscall":"open","path":"C:\\Program Files\\NoMansConnect\\nmssavetool\\saveCache.json"}
Mon Sep 11 2017 16:54:21 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4101 save file."
Mon Sep 11 2017 17:27:18 GMT+0100 (GMT Daylight Time):    "Initializing No Man's Connect 0.17.1"
Mon Sep 11 2017 17:27:21 GMT+0100 (GMT Daylight Time):    "Current location: -918:2:1391:0:78:0"
Mon Sep 11 2017 17:27:21 GMT+0100 (GMT Daylight Time):    "Username: IamIsbuck"
Mon Sep 11 2017 17:27:21 GMT+0100 (GMT Daylight Time):    "Active save file: C:\\Users\\Ian\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198321576578\\storage.hg"
Mon Sep 11 2017 17:27:21 GMT+0100 (GMT Daylight Time):    "Finished reading No Man's Sky v4101 save file."
-----------------------------------------
END

- How can this bug be reproduced -- SEE ABOVE

**Comment by jaszhix** [comment]
If you installed the app for all users you have to run it in admin mode. Either that, or the difficulty the game is set on is different than the one in NMC.
