### ISSUE TITLE
My username is protected

### ISSUE THREAD

**Issue by BlargBlargety** [jaszhix/NoMansConnect#55]
Issue template for bug reports:

- No Man's connect tells me my username is protected, even though it's the same computer and install location I've been using all along.
Username is **BlargBlargety**

- Windows version 10
- Absolute path to your storage_x.hg files
C:\Users\xyz\AppData\Roaming\HelloGames\NMS\st_76561197962390748

- Absolute path to your NMS install directory.
D:\Steam\steamapps\common\No Man's Sky

Use Pastebin or a small snippet relevant to the issue and include these files from Roaming/AppData/NoMansConnect:
- NMC.log
- settings.json

**I cannot find these files in Roaming/AppData.**

- How can this bug be reproduced?
Message pops up as program starts. I have version 0.18.0 and ran it successfully several times before it started producing this error.

**Comment by jaszhix** [comment]
The files should be available in Roaming/AppData/NoMansConnect.

**Comment by BlargBlargety** [comment]
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/1347776/NMC.log)

[settings.json.zip](https://github.com/jaszhix/NoMansConnect/files/1347783/settings.json.zip)

Ah, finally found them!

**Comment by BlargBlargety** [comment]
All right, the issue seems to be resolved now!

Thank you!
