### ISSUE TITLE
Keeps looping to explorer and asking for user name.

### ISSUE THREAD

**Issue by tiailds** [jaszhix/NoMansConnect#56]
Issue template for bug reports:

The programs starts by asking for my user name. When I put it in, the program restarts but as explorer and asks me again for the name.  I'm using Windows 10.

C:\Users\Owner\AppData\Roaming\HelloGames\NMS\DefaultUser
D:\Games\No Mans Sky

[NMC.log](https://github.com/jaszhix/NoMansConnect/files/1377160/NMC.log)
[settings.txt](https://github.com/jaszhix/NoMansConnect/files/1377168/settings.txt)
settings.json is copied to a txt.

**Comment by jaszhix** [comment]
Thanks, let's move this into the discussion in #53.
