### ISSUE TITLE
Save Game changes - NMC not remembering install/save directories in options

### ISSUE THREAD

**Issue by djehmli** [jaszhix/NoMansConnect#57]
The recent 1.38 save game changes have appeared to effect the NMC path options for save game and install directories.  It cannot find the file path locations.  File Path Locations are not saving in options since the update.  I had absolutely no issues prior to the stupid NMS save game changes.

When I go to djehmli/options and the save game directory, locate the directory click select folder.  No mans connect restarts.  Then I go to djehmli/options install directory, locate the directory, click select folder no mans connect restarts.  Start No Mans sky (currently on a space station) hop back into my ship, hop out of ship to create save point.  No log of position change to NMC.  This is in Normal mode.

Shut down NMS and NMC.  Open NMC, under options change to Survival save game.  Start NMS in survival mode, save current entity position, registers (old save game, not new) then any planet change afterwards, doesn't log positions.

Snippet of log below, on version 18.

Windows 10
C:\Users\djehm\AppData\Roaming\HelloGames\NMS\st_76561198052970098
C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky\Binaries

Sun Oct 01 2017 18:13:51 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sun Oct 01 2017 18:13:51 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage2.hg"
Sun Oct 01 2017 18:13:51 GMT-0400 (Eastern Daylight Time):    "Current location: -1665:7:-97:179:208:5"
Sun Oct 01 2017 18:30:24 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sun Oct 01 2017 18:30:39 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sun Oct 01 2017 18:34:00 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sun Oct 01 2017 18:34:15 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sun Oct 01 2017 18:37:30 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sun Oct 01 2017 18:37:45 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sun Oct 01 2017 18:40:10 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sun Oct 01 2017 18:40:25 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sun Oct 01 2017 18:43:21 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 11:35:28 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 07 2017 11:35:33 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 07 2017 11:35:38 GMT-0400 (Eastern Daylight Time):    "Current location: -1666:7:-97:179:232:4"
Sat Oct 07 2017 11:35:38 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 11:35:38 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 07 2017 11:35:38 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage3.hg"
Sat Oct 07 2017 11:43:16 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 11:43:31 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 07 2017 11:43:32 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 07 2017 11:43:34 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 11:43:34 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 07 2017 11:43:34 GMT-0400 (Eastern Daylight Time):    "Current location: -1666:7:-97:179:232:4"
Sat Oct 07 2017 11:43:34 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage3.hg"
Sat Oct 07 2017 12:01:12 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4103 save file."
Sat Oct 07 2017 12:01:27 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4103 save file."
Sat Oct 07 2017 12:02:54 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 07 2017 12:02:54 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 07 2017 12:02:56 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4103 save file."
Sat Oct 07 2017 12:02:56 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage5.hg"
Sat Oct 07 2017 12:02:56 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 07 2017 12:02:56 GMT-0400 (Eastern Daylight Time):    "Current location: -1666:7:-97:179:232:0"
Sat Oct 07 2017 12:08:27 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4103 save file."
Sat Oct 07 2017 12:08:42 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4103 save file."
Sat Oct 07 2017 12:43:54 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 07 2017 12:43:55 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 07 2017 12:43:57 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 12:43:57 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage.hg"
Sat Oct 07 2017 12:43:57 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 07 2017 12:43:57 GMT-0400 (Eastern Daylight Time):    "Current location: -1666:7:-97:179:232:2"
Sat Oct 07 2017 12:49:34 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 12:49:49 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 12:54:20 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 12:54:34 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 12:56:30 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 12:56:44 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 13:02:05 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 13:02:20 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 13:05:15 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 13:05:30 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 07 2017 13:06:10 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sun Oct 08 2017 10:28:59 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sun Oct 08 2017 10:28:59 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sun Oct 08 2017 10:29:08 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sun Oct 08 2017 10:29:08 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sun Oct 08 2017 10:29:08 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage.hg"
Sun Oct 08 2017 10:29:08 GMT-0400 (Eastern Daylight Time):    "Current location: -1666:7:-97:179:232:2"
Sun Oct 08 2017 11:32:26 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sun Oct 08 2017 11:32:27 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sun Oct 08 2017 11:32:29 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sun Oct 08 2017 11:32:29 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage.hg"
Sun Oct 08 2017 11:32:29 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sun Oct 08 2017 11:32:29 GMT-0400 (Eastern Daylight Time):    "Current location: -1666:7:-97:179:232:2"
Fri Oct 13 2017 11:13:21 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Fri Oct 13 2017 11:13:23 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Fri Oct 13 2017 11:13:32 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Fri Oct 13 2017 11:13:32 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage.hg"
Fri Oct 13 2017 11:13:32 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Fri Oct 13 2017 11:13:32 GMT-0400 (Eastern Daylight Time):    "Current location: -1666:7:-97:179:232:2"
Sat Oct 14 2017 12:00:13 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 14 2017 12:00:14 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 14 2017 12:00:34 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:00:34 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 14 2017 12:00:34 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage.hg"
Sat Oct 14 2017 12:00:34 GMT-0400 (Eastern Daylight Time):    "Current location: -1666:7:-97:179:232:2"
Sat Oct 14 2017 12:01:26 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:01:41 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:16:14 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 14 2017 12:16:15 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 14 2017 12:16:19 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:16:19 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 14 2017 12:16:19 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage10.hg"
Sat Oct 14 2017 12:16:19 GMT-0400 (Eastern Daylight Time):    "Current location: 1536:2:-928:0:29:1"
Sat Oct 14 2017 12:17:42 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:17:57 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:17:58 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:18:12 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:23:18 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:23:33 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:23:34 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:23:47 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:24:26 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 14 2017 12:24:27 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 14 2017 12:24:30 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:24:30 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage10.hg"
Sat Oct 14 2017 12:24:30 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 14 2017 12:24:30 GMT-0400 (Eastern Daylight Time):    "Current location: 1536:2:-928:0:29:1"
Sat Oct 14 2017 12:52:04 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 14 2017 12:52:04 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 14 2017 12:52:06 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:52:06 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage10.hg"
Sat Oct 14 2017 12:52:06 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 14 2017 12:52:06 GMT-0400 (Eastern Daylight Time):    "Current location: 1536:2:-928:0:29:1"
Sat Oct 14 2017 12:53:05 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 14 2017 12:53:05 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 14 2017 12:53:08 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:53:08 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage10.hg"
Sat Oct 14 2017 12:53:08 GMT-0400 (Eastern Daylight Time):    "Current location: 1536:2:-928:0:29:1"
Sat Oct 14 2017 12:53:08 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 14 2017 12:54:17 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 14 2017 12:54:17 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 14 2017 12:54:20 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 12:54:20 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage10.hg"
Sat Oct 14 2017 12:54:20 GMT-0400 (Eastern Daylight Time):    "Current location: 1536:2:-928:0:29:1"
Sat Oct 14 2017 12:54:20 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 14 2017 13:01:04 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 13:01:18 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 13:01:44 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 14 2017 13:01:44 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 14 2017 13:01:47 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 13:01:47 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage10.hg"
Sat Oct 14 2017 13:01:47 GMT-0400 (Eastern Daylight Time):    "Current location: 1536:2:-928:0:29:1"
Sat Oct 14 2017 13:01:47 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 14 2017 13:02:10 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 14 2017 13:02:10 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 14 2017 13:02:13 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 13:02:13 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 14 2017 13:02:13 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage10.hg"
Sat Oct 14 2017 13:02:13 GMT-0400 (Eastern Daylight Time):    "Current location: 1536:2:-928:0:29:1"
Sat Oct 14 2017 13:02:47 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 14 2017 13:02:48 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 14 2017 13:02:50 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 13:02:50 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 14 2017 13:02:50 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage10.hg"
Sat Oct 14 2017 13:02:50 GMT-0400 (Eastern Daylight Time):    "Current location: 1536:2:-928:0:29:1"
Sat Oct 14 2017 13:11:19 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 0.18.0"
Sat Oct 14 2017 13:11:20 GMT-0400 (Eastern Daylight Time):    "Failed to locate NMS install: path doesn't exist."
Sat Oct 14 2017 13:11:22 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."
Sat Oct 14 2017 13:11:22 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Sat Oct 14 2017 13:11:22 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\storage10.hg"
Sat Oct 14 2017 13:11:22 GMT-0400 (Eastern Daylight Time):    "Current location: 1536:2:-928:0:29:1"
Sat Oct 14 2017 13:14:50 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4104 save file."

**Comment by jaszhix** [comment]
Should be fixed in [v0.19.0](https://github.com/jaszhix/NoMansConnect/releases/tag/v0.19.0).
