### ISSUE TITLE
Location and Save file is never updated

### ISSUE THREAD

**Issue by RehabSubmarine** [jaszhix/NoMansConnect#58]
No Mans Sky Connect does not update current location correctly, even when switching game types and moving to new locations.  Switching game types, and restarting results in the same file and location being read each time.  This issue occurs even after resetting remote cache.   Each time No Mans Sky Connect seems to want to read storage5.hg

I am running Windows 10, and my path to my storage_x.hg files is : C:\Users\Strid\AppData\Roaming\HelloGames\NMS\st_76561197970509616

This is what the log looks like, note that I am changing the game type each time this reloads:
https://pastebin.com/Gqe9R7JV

And here is my settings.json:
https://pastebin.com/7V7X4LRR

And here is an image of my NMS save directory:
https://imgur.com/a/9UuZA

**Comment by jaszhix** [comment]
Thanks, this is related to the save file names being renamed, mentioned in #53. I'm going to push a fix hopefully within a few days.

**Comment by jaszhix** [comment]
Should be fixed in [v0.19.0](https://github.com/jaszhix/NoMansConnect/releases/tag/v0.19.0).
