### ISSUE TITLE
I tried teleporting - to an old location I had visited. It didn't work and No Man's Connect now shows another players name.

### ISSUE THREAD

**Issue by molyball** [jaszhix/NoMansConnect#59]
Issue template for bug reports:

I tried teleporting - to an old location I had visited. It didn't work and No Man's Connect now shows another players name.
 WIN 10
- Absolute path to your storage_x.hg files.
C:\Program Files (x86)\Steam\steamapps

Use Pastebin or a small snippet relevant to the issue and include these files from Roaming/AppData/NoMansConnect:
- NMC.log
- settings.json

- How can this bug be reproduced?

**Comment by jaszhix** [comment]
Duplicate #58, file name changes are the cause.

**Comment by jaszhix** [comment]
Fixed in [v0.19.0](https://github.com/jaszhix/NoMansConnect/releases/tag/v0.19.0).
