### ISSUE TITLE
No UI window displayed when running

### ISSUE THREAD

**Issue by CrankyCat** [jaszhix/NoMansConnect#6]
The installation runs as expected and, the dialogs for that display correctly, but when the application starts the window doesn't show. If I minimize and restore I can see a flash of an outline of the title bar but that's it. The mouse is affected as if the window is actually being displayed but nothing is. I tried started maximized and running as administrator but neither did anything different.

Windows 7 x64, Nvidia GTX Titan-X w/current 381.65 driver.

The absolute path to my saves is from the original release and the standard game mode.
C:\Users\bill\AppData\Roaming\HelloGames\NMS\st_76561198064585647

The installation is at:
C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky

NMC log says:
Thu Apr 20 2017 15:46:33 GMT-0600 (Mountain Daylight Time):    "Initializing No Man's Connect 0.7.1"
Thu Apr 20 2017 15:46:33 GMT-0600 (Mountain Daylight Time):    "Skipping process scan for Windows 7 user..."
Thu Apr 20 2017 15:46:35 GMT-0600 (Mountain Daylight Time):    "Username: Cranky-Cat"
Thu Apr 20 2017 15:46:35 GMT-0600 (Mountain Daylight Time):    "Current location: -996:-6:-1283:0:131:0"
Thu Apr 20 2017 15:46:35 GMT-0600 (Mountain Daylight Time):    "Active save file: C:\\Users\\bill\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198064585647\\storage3.hg"

I don't know how anyone else would reproduce this. I can't get different results.

**Comment by CrankyCat** [comment]
Well this didn't take long. Right after submitting this I decided to enable AERO and now it works. Normally I have it disabled and that seems to be the problem.

To reproduce, on Windows 7, right-click on the desktop and choose personalize from the context menu. Select "Windows 7 basic", "Windows Classic" or any of the non-Aero themes and NMC doesn't display the window.

**Comment by jaszhix** [comment]
@CrankyCat Following up on your issue with screenshot updating not working, do you have Aero enabled or disabled when this happens?

**Comment by CrankyCat** [comment]
I have Aero enabled now since I needed to do that in order for NMC to work.

**Comment by jaszhix** [comment]
Ok, I packaged up a test build that checks for Aero. If its disabled it will add frames to the window, which I suspect is part of the problem.

https://www.mediafire.com/?te9zny2145q4ngf

**Comment by CrankyCat** [comment]
The test version runs fine without Aero enabled. Thanks!

What triggers a location being uploaded? A new galactic address?

**Comment by jaszhix** [comment]
Whenever NMC starts up, or you save your game in NMS, it will send your save file's current address to the server, and if it doesn't exist on the server it will be stored in the database.

Glad to hear that worked for you!

**Comment by CrankyCat** [comment]
Thanks.
