### ISSUE TITLE
Unable to teleport and access username version 0.18.0

### ISSUE THREAD

**Issue by babmas122** [jaszhix/NoMansConnect#60]
Issue template for bug reports:

- Description of the problem
- Windows version
- Absolute path to your storage_x.hg files.
- Absolute path to your NMS install directory.

Use Pastebin or a small snippet relevant to the issue and include these files from Roaming/AppData/NoMansConnect:
- NMC.log
- settings.json
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/1403708/NMC.log)

- How can this bug be reproduced?

**Comment by jaszhix** [comment]
Please use the issue template. I'm working on a fix, thanks.

**Comment by jaszhix** [comment]
Fixed in [v0.19.0](https://github.com/jaszhix/NoMansConnect/releases/tag/v0.19.0).
