### ISSUE TITLE
Can't clear data

### ISSUE THREAD

**Issue by janusfenix** [jaszhix/NoMansConnect#62]
I played NMS for a while, and explored many planets. 
But then I deleted my save file and started a new save file, and would like to track this save's planets, without having it think my past planets were part of my journey.
I tried uninstalling NMC and deleting the appdata roaming NMC folder, and then reinstalling, but it immediately picked back up my old data.
I also tried changing my name on NMC, uninstalling / deleting as above, but it remembered it even though my username was no longer a match with my Steam / NMS name.

Is there a 'reset' / 'remove all of my data' function somewhere that I could use?

- Windows 10 Version	10.0.15063 Build 15063
- C:\Users\cbass\AppData\Roaming\HelloGames\NMS\st_76561197997998799
- C:\FastGames\Steam\steamapps\common\No Man's Sky

- https://pastebin.com/hrXdUaud
-https://pastebin.com/c5JuEPYX

**Comment by jaszhix** [comment]
Go to the tool menu and click "Reset Remote Cache" to clear remote cache (right list). The other locations you encounter are tied to your username on the server, and they are supposed to stay persistent. There is a feature request open in #43 for them to be removable.
