### ISSUE TITLE
Portal address

### ISSUE THREAD

**Issue by mhebrard** [jaszhix/NoMansConnect#63]
Hello. 
I just start to use NMConnect. 
I notice that it displays the Portal Address, but with "0" as the first glyph for each planet. 
If I well understand, you have the planet index, that is the last digit of the "Universe Address"... Then you should be able to display the good portal first glyph. 
Am I wrong ?

v1.0.1

**Comment by jaszhix** [comment]
The first glyph represents the portal number, according to the [NMS Wiki](https://nomanssky.gamepedia.com/Portal). I'm not sure if it correlates with the planet index or not. I don't have a way of pulling the portal number from the save file - just translating the hex address format. If we're able to confirm the portal number and planet index are the same, then I could use that.

**Comment by mhebrard** [comment]
As for the last patch, HG modify a bit the portal system. Now, each planet has only one portal, then the portal index correspond to the planet index. (0 for space station, 1 for first planet from the sun, moon is planet+1...).

**Comment by jaszhix** [comment]
Yes, but do we know portal 2 takes us to planet 2? That's what we need to know. I'll try to test sometime.

**Comment by mhebrard** [comment]
according to [this](https://www.reddit.com/r/NMSCoordinateExchange/wiki/tutorials/convert_portal_coordinates) and some test I heard about : "In the game version 1.38 each planet/moon has only 1 portal, and Portal Number=PlanetIndex". With the exception of the last planet of the system [here](https://www.reddit.com/r/NMSCoordinateExchange/wiki/guides/portals-how_to_find_and_use_them#wiki_portal_bug)

**Comment by jaszhix** [comment]
Fixed in 1.4.0
