### ISSUE TITLE
Cannot update username and locations not accurate

### ISSUE THREAD

**Issue by jbescup** [jaszhix/NoMansConnect#65]
- I changed my Steam username from "=DHWC= El Capitan" to "microcosmologist" about a month ago.  Since that time I have not used NMSconnect until just recently.  When I open up NMSconnect, I see that the username is still showing as "=DHWC= El Capitan" and none of my recent locations are logged.  I can try to manually override the username but it seems to have no effect.  When the program reopens, the username has reverted back to "=DHWC= El Capitan" again.  I have tried uninstalling and reinstalling NMSconnect but it still remembers me as "=DHWC= El Capitan" somehow.   Are there files hiding in some strange directory that it keeps referring to?  I have tried to hunt for that, but no luck.

- Windows 7
- NMS connect 1.0.1.exe-363-1-0-1
- Absolute path to your storage_x.hg files: C:\Users\Captain\AppData\Roaming\HelloGames\NMS\st_76561197973994897
- Absolute path to your NMS install directory: R:\Games\Steam\SteamApps\common\No Man's Sky

**Comment by jaszhix** [comment]
Look in C:\Users\Captain\AppData\Roaming\NoMansConnect and there should be an NMC.log file.
