### ISSUE TITLE
Some locations seem to be wrong or forged

### ISSUE THREAD

**Issue by darkbyte-pod** [jaszhix/NoMansConnect#67]
Issue template for bug reports:

- Description of the problem
Some locations seem to be wrong (see image included)

- Windows version
Windowd 10

- Absolute path to your storage_x.hg files.
Not related i believe

- Absolute path to your NMS install directory.
Not related i believe

- How can this bug be reproduced?
Just keep getting data from recent explorations list, eventually you will get something similar to the following picture:
![image](https://user-images.githubusercontent.com/13499617/36288107-245a59d6-1287-11e8-95d6-fc8c0b67d5a0.png)

This is using 1.0.2 (latest at this moment)

**Comment by jaszhix** [comment]
Yeah they are forged. Before I was writing a lot of checks to try to avoid this but I can't stop people from running older unpatched versions. I could force incompatibility on the API, and then maybe people ignorant of proper Windows software maintenance will be to blame when the app doesn't work? Its a really futile issue to me, and I don't think people have been very considerate with their use of the app.  Closing as wontfix.

**Comment by darkbyte-pod** [comment]
How about adding a way to remove a local forged entry? Not remove from the DB, just remove locally.

**Comment by jaszhix** [comment]
Maybe a self-moderation flagging option can be added. I'll re-open this for further discussion.

**Comment by darkbyte-pod** [comment]
I can see 2 things that could be good
1) The filtering option you suggested
2) selecting a rogue entry and hitting a "remove" or "delete" button

If filtering is on, rogue entries are not added to the player local list.

There is only 1 thing i am not sure about, will the rogue entries keep being requested and rejected?

**Comment by darkbyte-pod** [comment]
Actually, there is another option

The ability to mark an entry as not visible.

**Comment by jaszhix** [comment]
Currently there's two indexes of locations that stay cached - player's own and visited locations (left list) and the server's complete index gets cached as pagination occurs (right list) - it might make sense to have another list of locally blacklisted locations that the client checks when downloading remote locations for the server index.

**Comment by darkbyte-pod** [comment]
Would this list local list would build when filtering is enabled ?

or maybe just build the list from start even if not enabled, so that if i enable the filtering, it happens fast ?

**Comment by jaszhix** [comment]
Yeah the latter is closer to what I have in mind.

**Comment by jaszhix** [comment]
I deleted all the locations with invalid coordinates, most of them were from before I fixed the issue on the client. You will need to click "Reset remote cache" in the tool menu, or delete cache.json in AppData/Roaming/NoMansConnect for the changes to come into effect.

**Comment by jaszhix** [comment]
Should be fixed in 1.2.1+.
