### ISSUE TITLE
Loading Save Data

### ISSUE THREAD

**Issue by d3barr** [jaszhix/NoMansConnect#69]
Worked fine yesterday, now will not move from loading save data screen, have tried to select directory and save folders via the menu, have reinstalled, tried loading as admin, restarted the PC. Will not work at all, tried saving my game on a new planet, have restored a previous save. Nothing
Windows 10
Directory
C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky
Save
C:\Users\Debarr\AppData\Roaming\HelloGames\NMS\st_76561198140645003

Issue template for bug reports:

- Description of the problem
- Windows version
- Absolute path to your storage_x.hg files.
- Absolute path to your NMS install directory.

Use Pastebin or a small snippet relevant to the issue and include these files from Roaming/AppData/NoMansConnect:
- NMC.log
- settings.json

- How can this bug be reproduced?

**Comment by jaszhix** [comment]
Hi, I need you to zip up your Roaming/NoMansConnect folder and attach it here. What version of NMC are you running? The more info, the easier it is to pinpoint the cause.

You shouldn't need to run the app as admin anymore, local installation is the only option now.

**Comment by d3barr** [comment]
Its still doing it, tell you what ill try and download a few versions of the manager as then get back to youi and do what you've asked if i get no where. Its really strange as it was working without a issue 48 hours ago, still no luck this morning either. 
Its the upto date NMS as i purchased via steam so it updates automatically :-) thanks for the reply and ill get back to you if i have no luck 
Matt

**Comment by jaszhix** [comment]
Ah wow, my VPS provider did more security maintenance and I didn't notice. The server is now back up and running, sorry about that. Can you confirm its working now?

**Comment by d3barr** [comment]
Haha yeah it’s working now, thanks!!

**Comment by d3barr** [comment]
haha, yes its working! thanks for your support! Have a fantastic day!

**Comment by jaszhix** [comment]
Actually, I'll keep this open until I fix the issue preventing the production container from starting when the server does.
