### ISSUE TITLE
noman connect now thinks I am someone else?

### ISSUE THREAD

**Issue by cosmoderp** [jaszhix/NoMansConnect#72]
on the top right it suddenly became someone else is user name under settings after teleport.
 I tried:
going into admin
reset remote cache

**Comment by cosmoderp** [comment]
replaced the save with an older save still nothing

**Comment by cosmoderp** [comment]
ok so I fixed it..... I teleported back to my location in no mans connect.  As soon as it saved again it went back to my user name.

so dont know if that was a bug or a feature. So it simply attaches another user to you after you save after you save after teleporting.  It flip flops from my user name to theirs.

in my case it kept going back to that username.
teleport -- save -- DiabetikGam3r
teleport -- save -- seekker3
teleport -- save -- DiabetikGam3r
teleport -- save -- seekker3

so on.... I tried many time and that is how I reproduced what happened

**Comment by jaszhix** [comment]
Its a bug. Would you be able to provide your NMC.log and settings.json files in AppData/Roaming/NoMansConnect? You can attach them here or email them to me (address on profile).

**Comment by cosmoderp** [comment]
no problem here you go.
[log_and_settings.zip](https://github.com/jaszhix/NoMansConnect/files/2068790/log_and_settings.zip)

**Comment by jaszhix** [comment]
@cosmoderp Not sure if this is still reproducible for you, but I made a change in v1.1.2 that might fix it. It seems it was just changing the username after teleporting to a location, but the profiles were not getting mixed up. Please let me know if you continue to have issues with the username changing.
