### ISSUE TITLE
Manually Register Location Error: "Invalid coordinate format."

### ISSUE THREAD

**Issue by JoshAubrey** [jaszhix/NoMansConnect#74]
**- Description of the problem:** Manually Register Location Error: "Invalid coordinate format." Every location I attempt to enter produces this error, such as "0D3C:0078:03A3:0192". 
**Portal Link:** http://nmsportals.github.io/#1192F9BA453D
**Imgur Link:** https://imgur.com/a/4ti7gpb#ohmg023

**- Windows version:** Windows 10
**- Absolute path to your storage_x.hg files, Absolute path to your NMS install directory:**
"installDirectory":"G:\\SteamLibrary\\steamapps\\common\\No Man's Sky",
"saveDirectory":"C:\\Users\\Josh\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198044507745",

**- NMC.log** `Tue Jul 10 2018 23:22:34 GMT-0500 (Central Daylight Time):    "Initializing No Man's Connect 1.1.2"
Tue Jul 10 2018 23:22:36 GMT-0500 (Central Daylight Time):    "Finished reading No Man's Sky v4616 save file."
Tue Jul 10 2018 23:22:36 GMT-0500 (Central Daylight Time):    "Active save file: C:\\Users\\Josh\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198044507745\\save.hg"
Tue Jul 10 2018 23:22:36 GMT-0500 (Central Daylight Time):    "Current location: -165:3:-1781:0:122:1"
Tue Jul 10 2018 23:22:36 GMT-0500 (Central Daylight Time):    "Username: Josh Aubrey"
`
**- settings.json** `{"maximized":true,"maintenanceTS":1531201623765,"wallpaper":null,"installDirectory":"G:\\SteamLibrary\\steamapps\\common\\No Man's Sky","saveDirectory":"C:\\Users\\Josh\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198044507745","username":"Josh Aubrey","mapLines":false,"map3d":false,"mapDrawDistance":true,"show":{"Shared":true,"PS4":true,"Explored":true,"Center":true,"Favorite":true,"Current":true,"Selected":true,"Base":true},"filterOthers":false,"useGAFormat":true,"remoteLocationsColumns":1,"sortStoredByTime":false,"showHidden":true,"pollRate":60000,"mode":"normal","storedBases":[],"storedLocations":[{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":122,"PlanetIndex":1,"id":"-165:3:-1781:0:122:1","username":"Josh Aubrey","playerPosition":[-44997.3125,-66382.9921875,38049.0625,1],"playerTransform":[-0.3149276077747345,-0.9329425096511841,0.17446790635585785,1],"shipPosition":[-44993.3125,-66380.828125,38054.10546875,1],"shipTransform":[-0.5409550666809082,0.42540326714515686,-0.7255349159240723,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:122:1-b64e6079-74bb-4709-ab95-8c6bf3fea610.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530858366841,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:007A","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":122,"PlanetIndex":0,"id":"-165:3:-1781:0:122:0","username":"Josh Aubrey","playerPosition":[43982.6328125,13278.548828125,-43214.7734375,1],"playerTransform":[0.4420301020145416,0,-0.8970001935958862,1],"shipPosition":[43986.49609375,13276.3955078125,-43219.0625,1],"shipTransform":[-0.00010370786185376346,0,1.0000005960464478,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:122:0-2d76d6f5-5cbe-4e72-9f63-f6f38c96857a.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530856624270,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:007A","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":545,"PlanetIndex":0,"id":"-165:3:-1781:0:545:0","username":"Josh Aubrey","playerPosition":[91.55345153808594,-6186.4208984375,-1147.6409912109375,1],"playerTransform":[0.5166657567024231,0.20807892084121704,-0.8305177688598633,1],"shipPosition":[94.21415710449219,-6190.94970703125,-1151.19091796875,1],"shipTransform":[-0.08524485677480698,-0.2319466769695282,0.9689862132072449,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:545:0-f08ad601-c861-4142-bef6-6b310b6d2088.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530855561927,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:0221","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":545,"PlanetIndex":4,"id":"-165:3:-1781:0:545:4","username":"Josh Aubrey","playerPosition":[-1374646.5,-25850.923828125,319968.84375,1],"playerTransform":[-0.466227650642395,-0.6072927117347717,-0.643294095993042,1],"shipPosition":[-1374647.25,-25854.513671875,319974.3125,1],"shipTransform":[0.13720503449440002,0.9702304005622864,-0.19956958293914795,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:545:4-724831b7-d514-4733-b9bb-725b20bb11ba.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530852451450,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:0221","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":543,"PlanetIndex":3,"id":"-165:3:-1781:0:543:3","username":"Josh Aubrey","playerPosition":[695938.75,-108574.421875,-343732.75,1],"playerTransform":[-0.37688741087913513,-0.18533408641815186,-0.9075280427932739,1],"shipPosition":[695937.25,-108574.390625,-343738.96875,1],"shipTransform":[0.23712562024593353,0.6051304340362549,0.7599925398826599,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:543:3-509fbcfe-b5e9-47db-9beb-17733d4a5eae.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530851810795,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:021F","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":543,"PlanetIndex":6,"id":"-165:3:-1781:0:543:6","username":"Josh Aubrey","playerPosition":[69477.2890625,31996.865234375,1338569.875,1],"playerTransform":[0.9299744367599487,0.19764301180839539,-0.3099755048751831,1],"shipPosition":[69475.4375,32002.064453125,1338573.375,1],"shipTransform":[-0.2380611002445221,-0.9712460041046143,0.0029322104528546333,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:543:6-852629d6-7380-4ed3-a3fc-cd68c4d531f8.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530753810252,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:021F","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":478,"PlanetIndex":1,"id":"-165:3:-1781:0:478:1","username":"Josh Aubrey","playerPosition":[47166.33203125,-5252.79296875,-87258.3515625,1],"playerTransform":[0.6704592108726501,-0.7180001139640808,0.18697664141654968,1],"shipPosition":[47168.38671875,-5260.126953125,-87258.40625,1],"shipTransform":[-0.6513346433639526,0.6059651970863342,-0.45669424533843994,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:478:1-9dde4d52-0f14-498b-a532-a508a329ab9a.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530750680451,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:01DE","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":478,"PlanetIndex":0,"id":"-165:3:-1781:0:478:0","username":"Josh Aubrey","playerPosition":[-125.53544616699219,-6414.9365234375,491.37396240234375,1],"playerTransform":[-0.6655139327049255,0.037118736654520035,0.7454618811607361,1],"shipPosition":[-130.0331573486328,-6416.49951171875,494.84832763671875,1],"shipTransform":[0.26708805561065674,-0.04137032851576805,-0.9627838730812073,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:478:0-36180df5-eb76-466c-b902-385a136b9cbe.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530750409935,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:01DE","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":458,"PlanetIndex":2,"id":"-165:3:-1781:0:458:2","username":"Josh Aubrey","playerPosition":[469417.4375,-6588.9580078125,874571.5,1],"playerTransform":[0.5832533240318298,-0.8093823790550232,0.06867212057113647,1],"shipPosition":[469422.65625,-6585.06787109375,874570.4375,1],"shipTransform":[-0.8767852783203125,0.10642461478710175,0.46895796060562134,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:458:2-0fbc48da-244e-4594-9380-85601b8c83c8.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530686207990,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:01CA","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":458,"PlanetIndex":1,"id":"-165:3:-1781:0:458:1","username":"Josh Aubrey","playerPosition":[-148636.359375,27370.783203125,-73485.7734375,1],"playerTransform":[0.9020553827285767,0.4214450418949127,-0.09316803514957428,1],"shipPosition":[-148630.703125,27373.55859375,-73483.765625,1],"shipTransform":[-0.9278662204742432,-0.0590229257941246,0.3682129383087158,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:458:1-72b069c1-8bfa-4052-b4db-0b6ea41ba048.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530684830283,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:01CA","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":458,"PlanetIndex":0,"id":"-165:3:-1781:0:458:0","username":"Josh Aubrey","playerPosition":[329.70745849609375,-6007.87158203125,68.28392791748047,1],"playerTransform":[0.7201869487762451,0.4436612129211426,-0.5333813428878784,1],"shipPosition":[333.0394592285156,-6005.70703125,71.79228210449219,1],"shipTransform":[-0.6025259494781494,-0.7851614952087402,-0.1431228369474411,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:458:0-c2d132ac-a4d1-4d17-ae8b-6013b5587095.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530683863751,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:01CA","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":438,"PlanetIndex":1,"id":"-165:3:-1781:0:438:1","username":"Josh Aubrey","playerPosition":[32719.8125,19288.513671875,91591.3125,1],"playerTransform":[-0.9824671149253845,0.17051999270915985,0.07537486404180527,1],"shipPosition":[32715.267578125,19287.314453125,91595.1328125,1],"shipTransform":[0.8011509776115417,-0.5404261946678162,-0.2570926547050476,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:438:1-a6cde39e-1231-47ab-bf5c-9fcdb4297e3b.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530598553219,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:01B6","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":438,"PlanetIndex":0,"id":"-165:3:-1781:0:438:0","username":"Josh Aubrey","playerPosition":[-101.14311218261719,-7015.98095703125,-1076.37646484375,1],"playerTransform":[0.36376699805259705,-0.42443326115608215,-0.8291743397712708,1],"shipPosition":[-97.5956802368164,-7019.60595703125,-1079.62451171875,1],"shipTransform":[0.08487935364246368,0.4731977581977844,0.876857578754425,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:438:0-88f3cb98-c979-4856-babd-0f53d05b68de.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530596630098,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:01B6","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":405,"PlanetIndex":0,"id":"-165:3:-1781:0:405:0","username":"Josh Aubrey","playerPosition":[-263.36956787109375,-6317.5625,-444.0250244140625,1],"playerTransform":[-0.07554277032613754,0.1940903663635254,-0.9780707359313965,1],"shipPosition":[-263.2878723144531,-6322.1640625,-448.38604736328125,1],"shipTransform":[0.5056837201118469,-0.2164030373096466,0.835137128829956,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"","mods":[],"manuallyEntered":false,"timeStamp":1530592957581,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:0195","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":405,"PlanetIndex":2,"id":"-165:3:-1781:0:405:2","username":"Josh Aubrey","playerPosition":[409082.125,107856.1015625,128147.5703125,1],"playerTransform":[0.4539075791835785,-0.5005279779434204,0.7371836304664612,1],"shipPosition":[409086.78125,107852.4140625,128150.2578125,1],"shipTransform":[-0.32376545667648315,0.12794408202171326,-0.937446653842926,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:405:2-6605e8ee-5f04-46cb-8f63-fab1c6847a26.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530085187791,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:0195","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":405,"PlanetIndex":3,"id":"-165:3:-1781:0:405:3","username":"Josh Aubrey","playerPosition":[72805.9765625,-102411.9375,256014.5,1],"playerTransform":[-0.549045205116272,-0.652351975440979,0.5224809050559998,1],"shipPosition":[72804.21875,-102416.953125,256018.171875,1],"shipTransform":[-0.08685703575611115,0.12697523832321167,-0.9880957007408142,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:405:3-e1bd97e1-6b5f-4348-9e22-1c7c02e1bfd7.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530084631997,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:0195","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":37,"PlanetIndex":0,"id":"-165:3:-1781:0:37:0","username":"Josh Aubrey","playerPosition":[63.10803985595703,-6659.0869140625,-1244.8270263671875,1],"playerTransform":[0.4827618896961212,-0.1606772392988205,-0.860885500907898,1],"shipPosition":[65.5211410522461,-6664.74951171875,-1246.3438720703125,1],"shipTransform":[-0.04609647020697594,0.1791234165430069,0.982746422290802,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:37:0-2abdae3c-0d80-484c-9e60-9ce741dc71ab.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530082831752,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:0025","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":37,"PlanetIndex":1,"id":"-165:3:-1781:0:37:1","username":"Josh Aubrey","playerPosition":[24964.21875,7308.0498046875,186857.765625,1],"playerTransform":[0.5626130700111389,-0.7900506258010864,-0.2434881180524826,1],"shipPosition":[24961.810546875,7302.74462890625,186855.078125,1],"shipTransform":[-0.36455628275871277,0.8863739967346191,0.28537777066230774,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"/media/NMSLocation-Josh Aubrey--165:3:-1781:0:37:1-56d88142-34c8-4a5a-894d-957c0595d9ef.jpg","mods":[],"manuallyEntered":false,"timeStamp":1530081621853,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:0025","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":37,"PlanetIndex":2,"id":"-165:3:-1781:0:37:2","username":"Josh Aubrey","playerPosition":[396168.71875,-75838.4765625,-183468.703125,1],"playerTransform":[-0.39189448952674866,-0.747961699962616,-0.5356977581977844,1],"shipPosition":[396169.59375,-75843,-183472.1875,1],"shipTransform":[0.39688754081726074,0.9123945832252502,0.10008298605680466,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"","mods":[],"manuallyEntered":false,"timeStamp":1530079603282,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:0025","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":89,"PlanetIndex":3,"id":"-165:3:-1781:0:89:3","username":"Josh Aubrey","playerPosition":[-630953.125,32331.013671875,949624.375,1],"playerTransform":[0.8260050415992737,-0.28833913803100586,0.4843307137489319,1],"shipPosition":[-630953.1875,32326.654296875,949625.6875,1],"shipTransform":[0.25599461793899536,0.8886985778808594,0.38037073612213135,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"","mods":[],"manuallyEntered":false,"timeStamp":1530076157765,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:0059","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":89,"PlanetIndex":0,"id":"-165:3:-1781:0:89:0","username":"Josh Aubrey","playerPosition":[-115.1077880859375,-6248.705078125,437.4649963378906,1],"playerTransform":[-0.6306670308113098,0.04965781420469284,0.7744632959365845,1],"shipPosition":[-118.4432144165039,-6252.626953125,441.16510009765625,1],"shipTransform":[0.226324200630188,-0.37568357586860657,-0.898687481880188,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"","mods":[],"manuallyEntered":false,"timeStamp":1530073519265,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:0059","name":"","description":"","score":0},{"VoxelX":-165,"VoxelY":3,"VoxelZ":-1781,"SolarSystemIndex":89,"PlanetIndex":2,"id":"-165:3:-1781:0:89:2","username":"Josh Aubrey","playerPosition":[1004612.5,45125.16796875,387922.0625,1],"playerTransform":[0.5875226259231567,-0.8041303753852844,0.09050805866718292,1],"shipPosition":[1004610.625,45123.609375,387922.4375,1],"shipTransform":[-0.6479322910308838,0.7581656575202942,-0.07327085733413696,1],"galaxy":0,"distanceToCenter":178862.9363507152,"translatedX":1882,"translatedZ":266,"translatedY":130,"base":false,"baseData":null,"upvote":false,"image":"","mods":[],"manuallyEntered":false,"timeStamp":1530067615350,"version":4616,"jumps":448,"translatedId":"075A:0082:010A:0059","name":"","description":"","score":1}],"favorites":[],"autoCapture":true,"ps4User":false,"compactRemote":false,"offline":false,"showOnlyNames":false,"showOnlyDesc":false,"showOnlyScreenshots":true,"showOnlyGalaxy":true,"showOnlyBases":false,"showOnlyPC":false,"showOnlyCompatible":true,"sortByDistance":false,"sortByModded":false,"remoteLocations":{"results":[],"count":0,"next":null,"prev":null},"page":null}`

**Comment by jaszhix** [comment]
Fixed in v1.1.3
