### ISSUE TITLE
Enhancement request for the Stored locations window - additional sorts and filters

### ISSUE THREAD

**Issue by djehmli** [jaszhix/NoMansConnect#79]
Would it be possible to add a few more sort and filter options to the stored locations?

Potentials would be:
Sort by Created Date
Sort by Names
Sort by Descriptions
Filter by Base
Filter by Screen Shot

After clearing the App folder after the last incident, my stored locations screen is a bit unruly.  Since I have screen shots of every galaxy, system and planet I've visited,  I decided to try to update names and organize then got lost :)

These would be nice to haves, if they are feasible.

**Comment by jaszhix** [comment]
Yeah, sounds feasible. Its supposed to show favorites at the top and the rest sort by date, but now noticing the order is a bit messed up.

**Comment by jaszhix** [comment]
Added more sorting/filtering options in 1.3.0.
