### ISSUE TITLE
Base restoration

### ISSUE THREAD

**Issue by MickCasanova** [jaszhix/NoMansConnect#80]
Base restoration function doesn't work properly.
Windows 7

I attempted to restore a base using the function in NMC. What I got was very strange. The base restored on edge as if it were built diagonal to the ground. Of course the exocraft tumbled down, and anything else that wasn't attached. Needless to say, the function doesn't seem to work in Next.   

Just so you know, I tried this a few different ways. First I used the base I had in the last version. When it was restored on edge, I used a different save, and saved the base using the game mechanics., then resaved it in NMC. Same result when I attempted to restore it using NMC.

I am using version 1.5.3 of NMS.

**Comment by jaszhix** [comment]
Yeah, pre-1.5 bases are not going to work. I was able to import a base that was built in the location originally its being imported into (in 1.5, after botched imports like you ran into), and as a result, in the patch notes I suggest only using it for backups. I didn't write the logic behind the base restoration, that was @monkeyman192. I'm not sure how to fix it, but it still can be useful for backing up a base's current state. Hopefully something can be done it about it in the future.
