### ISSUE TITLE
NMC window disappears after trying to resize window

### ISSUE THREAD

**Issue by Tkdmaster** [jaszhix/NoMansConnect#81]
- Entire Connect window seems to disappear if you attempt to drag-resize the window from the top right corner. The window will show in the taskbar preview hover, but completely disappears from view, and is unable to be returned to visibility without a complete reinstall of the program.

- Windows 10

- Reproducable by simply drag-resizing form the top right corner.

**Comment by jaszhix** [comment]
I can't reproduce this.

**Comment by jaszhix** [comment]
You don't need to uninstall the app if this happens - just delete window-state.json in AppData/Roaming/NoMansConnect. This was a bug that I recently fixed, so make sure you are running the newest version. I only have time to support the very newest version. You didn't provide NMC.log, tell me which version you're using, or tell me what version of windows you are running, e.g. Windows 10 1709, 1803 etc.

**Comment by Tkdmaster** [comment]
Apologies, here is some mor einfo:

NMC.log : https://pastebin.com/5f8sCriK

NMC is version 1.2.1, so latest as far as I can tell.
windows 10 version 1803

I just attempted this again, and it didn't reproduce exactly as it had previously. It does though, if you move the entire window slightly by dragging the top bar of the program, and then try to resize it.

**Comment by jaszhix** [comment]
No problem, I have the minimum size for the window set to 1410x1040, so I'm not sure how you are able to make it collapse into a dot. Its not budging below that size for me. I'm running 1803 as well.

window-state.json
```
{"width":3440,"height":1410,"x":3113,"y":633,"isMaximized":true,"isFullScreen":false,"displayBounds":{"x":3440,"y":339,"width":2560,"height":1080}}
```
