### ISSUE TITLE
Writing Save Data

### ISSUE THREAD

**Issue by ThePenitence** [jaszhix/NoMansConnect#86]
So I was posting about my issues with NMC on the nexusmods post of this but figured I should come here for easier sharing of info and so I can know when there's a reply.

My issue is simply NMC doesn't write any changes to my save file, it knows what my current save file is at any moment (I can see the tooltip say so when I hover over "Teleport To"). Even tried the adding credits button and that made no changes either.

Windows 10 Pro
C:\Users\Brian Perez\AppData\Roaming\HelloGames\NMS\st_76561198044279579
D:\Program Files (x86)\Steam\steamapps\common\No Man's Sky

Issue template for bug reports:

- Description of the problem
- Windows version
- Absolute path to your storage_x.hg files.
- Absolute path to your NMS install directory.

Use Pastebin or a small snippet relevant to the issue and include these files from Roaming/AppData/NoMansConnect:
- NMC.log
- settings.json

- How can this bug be reproduced?

**Comment by jaszhix** [comment]
I just responded there - can you attach NMC.log?

**Comment by jaszhix** [comment]
Try changing it to `C:\Users\Brian Perez\AppData\Roaming\HelloGames\NMS` - that's the directory it will find by default if no configuration is made.

**Comment by ThePenitence** [comment]
I've had it as both /NMS and /NMS/st.. I just keep switching it to see if it'll end up working. 
Also github won't process the file, tried it several times.

**Comment by jaszhix** [comment]
Ok, can you use [pastebin](https://pastebin.com/)?

**Comment by ThePenitence** [comment]
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/2260683/NMC.log)
Actually cancel that, it was NoScript not allowing githubrepository something or other to run.

**Comment by jaszhix** [comment]
Ahh, it has to do with a space in the path breaking it. Should be an easy fix.

**Comment by ThePenitence** [comment]
Oh you're saying the problem is the space in the user directory? I can see that, wasn't my choice to put my full name for my user profile, Windows 10 just does what it wants and leaves little room for change lol

**Comment by jaszhix** [comment]
Yeah, know what you mean. Though I just use a local account, you can switch to one in the settings somewhere. :)

Can you test and see if this works? Thanks. http://www.mediafire.com/file/apvqo8mnm2c78j4/NoMansConnect_Setup_1.3.1.exe/file

**Comment by ThePenitence** [comment]
Yeah I just started working on the process of making one, it's not the first time I've had an issue because of the directory so might as well fix it now. And yeah I'll try it out before I finish changing things.

**Comment by ThePenitence** [comment]
Yeah it works now as intended, thanks for the fix. I'll see to doing about that account thing now lol
