### ISSUE TITLE
Portal address always shows glyphs for first planet/portal

### ISSUE THREAD

**Issue by Randshot** [jaszhix/NoMansConnect#91]
I noticed that the *Portal Address* field always shows the glyphs for the first planet/portal.
If I remember right, in the NEXT update, there is a portal on each planet and each one of them has a *unique* portal address (glyphs).
042F:0078:0D55:0021
For reference, you can look at [nmsportals](http://nmsportals.github.io/#0021F9556C30) and use the following galactic address: `042F:0078:0D55:0021`
If you change the *Portal Number* before pasting in the galactic address, you will see that the glyphs and portal address will change as well.

Below is an example (the first glyph changes):
![portal1](https://user-images.githubusercontent.com/7832423/43790197-2c7d767a-9a72-11e8-8c20-a988822ec557.PNG)
![portal2](https://user-images.githubusercontent.com/7832423/43790198-2c9584ae-9a72-11e8-8a90-2d3add417498.PNG)

**Comment by jaszhix** [comment]
Yeah portals are slightly off at the moment, I'll try to look into it next. Also see #63.

**Comment by Randshot** [comment]
Ok, I will close this one then, since it is a duplicate.
