### ISSUE TITLE
Starts and then just shows background and nothing else

### ISSUE THREAD

**Issue by passivepixels** [jaszhix/NoMansConnect#93]
I haven't been able to get version 1.50 working properly (NoMansConnect Setup 1.5.0.exe-363-1-5-0.exe from nexus). It starts and looks okay, it renders the top settings bar and has the wheel going around in the screen with loading etc. IE: 
https://i.imgur.com/cIfl1KQ.jpg

Just after 'syncing discoveries', everything disappears and I just get the background screen with nothing else, IE: https://i.imgur.com/GRQ8B2P.jpg
And that's it :(

Tried going back to 1.40 which works fine in that the graphics don't disappear but it doesn't appear to work with NMS 1.57. 

Running windows 7. Everything worked great for me up until this version of NMC.

NMC.log:
1534578496783:    Initializing No Man's Connect 1.5.0 
1534578498610:    Failed to locate NMS install: path doesn't exist. 
1534578498611:    SAVE DIRECTORY:  C:\Users\Simo\AppData\Roaming\HelloGames\NMS 
1534578498610:    Skipping process scan... 
1534578499162:    Finished reading No Man's Sky v4626 save file. 
1534578499186:    Active save file: C:\Users\Simo\AppData\Roaming\HelloGames\NMS\st_76561197983556956\save.hg 
1534578499186:    Current location: -435:3:1684:0:374:3 
1534578499186:    Username: charliedelta 

Settings.json: https://pastebin.com/UYU8kEZa

- Absolute path to your storage_x.hg files.
C:\Users\Simo\AppData\Roaming\HelloGames\NMS\st_76561197983556956
- Absolute path to your NMS install directory.
C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky

- How can this bug be reproduced?
Starting NMC.

**Comment by passivepixels** [comment]
Additionally, just tried 1.50 on my laptop (which doesn't have nms installed) in offline mode (internet disabled) with a save file. Loads fine and renders graphics (ie menu and galaxy map grid). The moment I choose to load a save file (tried 2 different 1.57 saves, one in a station, the other at a planet) the same issue occurs, everything disappears (though I get left looking at a black screen instead of the background).
If I quit NMC and restart it will automatically go to the black screen mode. Same too if i move the save game to a different directory.
If i uninstall NMC and reinstall it, it will render the menu etc, up until I load a save at which it goes blank as per above.

**Comment by passivepixels** [comment]
Also just read the notes re: ui not rendering if sort by screenshots is enabled. It is possible (i'm not sure) i had that selected prior to 1.50 but there is no way for me to unselect now as i'm caught in a catch-22.

**Comment by pandapewpew** [comment]
i have the same problem after updating

**Comment by Grumpah** [comment]
Same :(

**Comment by jaszhix** [comment]
Thanks for the report. I am looking into this - have you guys tried clearing the contents of AppData/Roaming/NoMansConnect as a temporary workaround? You may need to manually select your save data directory afterwards.

**Comment by Grumpah** [comment]
Clear all of the contents? Delete them all?

**Comment by UjCbFwtBayFM** [comment]
How I managed to launch the app (not a reliable fix/workaround) :
* Clear %AppData%\NoMansConnect
* Launch the app - it may or may not work correctly - if it does, don't touch anything and close it.
* Open `settings.json` 
  * remove `installDirectory` variable (should be set to `null`)
  * add `saveDirectory` with the correct value (don't forget using double \) right after `username`
  * save it
* Launch the app

It launched successfully the first and second time, all my previous discoveries are displaying. On first time I only opened / closed the app. On second time I opened Settings and closed the app without any modification. App won't open again after that. Had to re-clean the AppData folder. Deleting `NMC.log` before each launch seems to help. I also had the game open in the background the whole time I worked on the files.
When trying to use a 1.4 backup file, it gets a lot smaller (around a third smaller) after using it with 1.5. Might be nothing, might be something ?

**Comment by jaszhix** [comment]
I have a WIP version that fixes a few bugs, but I'm not done. NMC uses [Sentry](https://sentry.io), which automatically reports errors in the client (and server) as they occur. Still going through the list (its long 🙂).

http://www.mediafire.com/file/my03ztcc8sqwa3c/NoMansConnect_Setup_1.5.1.test.1.exe/file

**Comment by passivepixels** [comment]
1.51 fixed it for me! Many thanks for your time and effort, much appreciated.
