### ISSUE TITLE
Wrong Player Name

### ISSUE THREAD

**Issue by molyball** [jaszhix/NoMansConnect#94]
Issue template for bug reports:
 NMC opens with the wrong player name (seabug25) My name is Player name  Molyball
 NMC wont let me override the wrong name.
Win 10 64 pro
NMS on Steam

**Comment by jaszhix** [comment]
Hi, I deployed a patch to the server that will at least allow the username override to not fail in this scenario. Please let me know if attempting this workaround works.

**Comment by molyball** [comment]
Hi, OK now both mine and my wife's are correct now.
Thanks

**Comment by PantACRO4life** [comment]
Hi I have the same issue  just reinstall reopen nmc after a year and my name switch to something else then it should.

My name PantACRO4life
What it switch for lux3y
and I cannot change it cuz it say to turn off protection when its already off.

I tied fresh install (cleared roaming and local appdata) but it does the same with the same username.
