### ISSUE TITLE
[SOLVED} NMS Connect is stuck on "checking for Mods

### ISSUE THREAD

**Issue by Quovad** [jaszhix/NoMansConnect#95]
Ï recently installed Connect, on start up it does detect my online / game name but then hangs on "checking for mods". I have no mods installed!

This reproduces at any new start of program

**Comment by Grumpah** [comment]
That was the same with mine.  Uninstalled, downloaded new version now it loads and before I can do anything just shows the background :( why did I warp to the complete other side of the galaxy last night :(

**Comment by MickCasanova** [comment]
I was on 1.40rc... Had this happen today. Hung like it once did for me before. Then I found out 1.50 was available. I installed, and everything was just fine. I might add I never got a notification of a new version when I started NMC today... It just sat at an infinite loading screen. So, I figured I would check for an update the old fashioned way. That's when I saw 1.50... Now everything is fine again...

**Comment by jaszhix** [comment]
Ah, that's interesting - its supposed to intercept the old version check and send instructions that the older clients are API incompatible. Was a long night, will try to fix this up.

**Comment by Quovad** [comment]
[SOLVED] Yes, update to 1.5 has resolved this Bug ;-)

**Comment by jaszhix** [comment]
Older versions should get a server notice about upgrading now.
