### ISSUE TITLE
Cannot Teleport 1.5.0

### ISSUE THREAD

**Issue by Pampus78** [jaszhix/NoMansConnect#96]
Hello,
Problem with option Teleport To in 1.5.0. version. After using this option, I have no changing in my save menu. In 1.4.0. everything were fine.

- Description of the problem
- Windows version 10 x64
- Absolute path to your storage_x.hg files:
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/2299739/NMC.log)

C:\Users\D\AppData\Roaming\HelloGames\NMS\st_76561198017470239
- Absolute path to your NMS install directory: 
C:\Users\D\AppData\Roaming\HelloGames\NMS\

[NMC.log](https://github.com/jaszhix/NoMansConnect/files/2299743/NMC.log)

**Comment by jaszhix** [comment]
From the log:
```
1534613084686:    SAVE DIRECTORY:  C:\Users\D\AppData\Roaming\HelloGames\NMS\st_76561198017470239 
1534613127839:    Unable to backup save file before writing:  EISDIR: illegal operation on a directory, read 
```

Hi, couple questions - does the save directory exist? Does your user have read/write access to the save directory? Try right clicking the directory (HelloGames, NMS, and/or st_76561198017470239 ) -> Properties -> Security ->Advanced -> is Owner your Windows user, and under Access does it list "Full control" by your user?

You can also test this WIP version of NMC.

http://www.mediafire.com/file/fs44nvaxe9di38v/NoMansConnect_Setup_1.5.1.test.2.exe/file
